/* written by tools/get-recordings.py - do not edit */
window.RECORDINGS = {
 "af": {
  "asseblief": "asseblief.mp3",
  "dankie": "dankie.mp3",
  "drie": "drie.mp3",
  "een": "een.mp3",
  "hallo": "hallo.mp3",
  "hoeveel": "hoeveel.mp3",
  "ja": "ja.mp3",
  "jammer": "jammer.mp3",
  "kos": "kos.mp3",
  "liefde": "liefde.mp3",
  "nee": "nee.mp3",
  "toilet": "toilet.mp3",
  "totsiens": "totsiens.mp3",
  "twee": "twee.mp3",
  "vriend": "vriend.mp3",
  "water": "water.mp3"
 },
 "am": {
  "ሁለት": "ሁለት.mp3",
  "ምግብ": "ምግብ.mp3",
  "ሰላም": "ሰላም.mp3",
  "ስንት": "ስንት.mp3",
  "ሶስት": "ሶስት.mp3",
  "አመሰግናለሁ": "አመሰግናለሁ.mp3",
  "አንድ": "አንድ.mp3",
  "አዎ": "አዎ.mp3",
  "አይደለም": "አይደለም.mp3",
  "እባክህ": "እባክህ.mp3",
  "ውሃ": "ውሃ.mp3",
  "ይቅርታ": "ይቅርታ.mp3",
  "ደህና ሁን": "ደህና_ሁን.mp3",
  "ጓደኛ": "ጓደኛ.mp3",
  "ፍቅር": "ፍቅር.mp3"
 },
 "ar": {
  "Six letters (ا د ذ ر ز و) never join to the left — the word breaks after them.": "Six_letters_ا_د_ذ_ر_ز_و_never_join_to_the_left_the_word_brea.mp3",
  "آسف": "آسف.mp3",
  "أحبك": "أحبك.mp3",
  "أربعة": "أربعة.mp3",
  "ا": "ا.mp3",
  "اثنان": "اثنان.mp3",
  "اسم": "اسم.mp3",
  "السلام عليكم": "السلام_عليكم.mp3",
  "ب": "ب.mp3",
  "بـ": "بـ.mp3",
  "بيت": "بيت.mp3",
  "بَ": "ب.mp3",
  "بُ": "ب.mp3",
  "بِ": "ب.mp3",
  "بّ": "ب.mp3",
  "بْ": "ب.mp3",
  "ت": "ت.mp3",
  "ث": "ث.mp3",
  "ثلاثة": "ثلاثة.mp3",
  "ج": "ج.mp3",
  "جميل": "جميل.mp3",
  "ح": "ح.mp3",
  "حمام": "حمام.mp3",
  "خ": "خ.mp3",
  "خبز": "خبز.mp3",
  "خمسة": "خمسة.mp3",
  "د": "د.mp3",
  "ذ": "ذ.mp3",
  "ر": "ر.mp3",
  "ز": "ز.mp3",
  "س": "س.mp3",
  "ش": "ش.mp3",
  "شاي": "شاي.mp3",
  "شكرا": "شكرا.mp3",
  "ص": "ص.mp3",
  "صباح الخير": "صباح_الخير.mp3",
  "صديق": "صديق.mp3",
  "ض": "ض.mp3",
  "ط": "ط.mp3",
  "ظ": "ظ.mp3",
  "ع": "ع.mp3",
  "غ": "غ.mp3",
  "ـب": "ـب.mp3",
  "ـبـ": "ـبـ.mp3",
  "ف": "ف.mp3",
  "ق": "ق.mp3",
  "قطة": "قطة.mp3",
  "ك": "ك.mp3",
  "كم الثمن": "كم_الثمن.mp3",
  "ل": "ل.mp3",
  "لا": "لا.mp3",
  "لا أفهم": "لا_أفهم.mp3",
  "لذيذ": "لذيذ.mp3",
  "م": "م.mp3",
  "مدرسة": "مدرسة.mp3",
  "مرحبا": "مرحبا.mp3",
  "مصر": "مصر.mp3",
  "مع السلامة": "مع_السلامة.mp3",
  "معلم": "معلم.mp3",
  "من فضلك": "من_فضلك.mp3",
  "ن": "ن.mp3",
  "نعم": "نعم.mp3",
  "ه": "ه.mp3",
  "و": "و.mp3",
  "واحد": "واحد.mp3",
  "ي": "ي.mp3"
 },
 "bg": {
  "благодаря": "благодаря.mp3",
  "вода": "вода.mp3",
  "да": "да.mp3",
  "две": "две.mp3",
  "довиждане": "довиждане.mp3",
  "едно": "едно.mp3",
  "здравей": "здравей.mp3",
  "извинете": "извинете.mp3",
  "колко": "колко.mp3",
  "любов": "любов.mp3",
  "моля": "моля.mp3",
  "не": "не.mp3",
  "приятел": "приятел.mp3",
  "тоалетна": "тоалетна.mp3",
  "три": "три.mp3",
  "храна": "храна.mp3"
 },
 "bn": {
  "এক": "এক.mp3",
  "কত": "কত.mp3",
  "খাবার": "খ_ব_র.mp3",
  "জল": "জল.mp3",
  "তিন": "ত_ন.mp3",
  "দয়া করে": "দয_কর.mp3",
  "দুঃখিত": "দ_খ_ত.mp3",
  "দুই": "দ_ই.mp3",
  "ধন্যবাদ": "ধন_যব_দ.mp3",
  "নমস্কার": "নমস_ক_র.mp3",
  "না": "ন.mp3",
  "বন্ধু": "বন_ধ.mp3",
  "বাথরুম": "ব_থর_ম.mp3",
  "বিদায়": "ব_দ_য.mp3",
  "ভালোবাসা": "ভ_ল_ব_স.mp3",
  "হ্যাঁ": "হ_য.mp3"
 },
 "ca": {
  "adéu": "adéu.mp3",
  "aigua": "aigua.mp3",
  "amic": "amic.mp3",
  "amor": "amor.mp3",
  "dos": "dos.mp3",
  "gràcies": "gràcies.mp3",
  "hola": "hola.mp3",
  "lavabo": "lavabo.mp3",
  "menjar": "menjar.mp3",
  "no": "no.mp3",
  "perdó": "perdó.mp3",
  "quant": "quant.mp3",
  "si us plau": "si_us_plau.mp3",
  "sí": "sí.mp3",
  "tres": "tres.mp3",
  "un": "un.mp3"
 },
 "cs": {
  "ahoj": "ahoj.mp3",
  "ano": "ano.mp3",
  "dva": "dva.mp3",
  "děkuji": "děkuji.mp3",
  "jeden": "jeden.mp3",
  "jídlo": "jídlo.mp3",
  "kolik": "kolik.mp3",
  "láska": "láska.mp3",
  "na shledanou": "na_shledanou.mp3",
  "ne": "ne.mp3",
  "promiňte": "promiňte.mp3",
  "prosím": "prosím.mp3",
  "přítel": "přítel.mp3",
  "tři": "tři.mp3",
  "voda": "voda.mp3",
  "záchod": "záchod.mp3"
 },
 "da": {
  "en": "en.mp3",
  "farvel": "farvel.mp3",
  "hej": "hej.mp3",
  "hvor meget": "hvor_meget.mp3",
  "ja": "ja.mp3",
  "kærlighed": "kærlighed.mp3",
  "mad": "mad.mp3",
  "nej": "nej.mp3",
  "tak": "tak.mp3",
  "to": "to.mp3",
  "toilet": "toilet.mp3",
  "tre": "tre.mp3",
  "undskyld": "undskyld.mp3",
  "vand": "vand.mp3",
  "ven": "ven.mp3",
  "vær så god": "vær_så_god.mp3"
 },
 "de": {
  "Essen": "Essen.ogg",
  "Freund": "Freund.ogg",
  "Liebe": "Liebe.ogg",
  "Toilette": "Toilette.ogg",
  "Wasser": "Wasser.ogg",
  "bitte": "bitte.ogg",
  "danke": "danke.ogg",
  "drei": "drei.mp3",
  "eins": "eins.ogg",
  "entschuldigung": "entschuldigung.mp3",
  "hallo": "hallo.ogg",
  "ja": "ja.ogg",
  "nein": "nein.mp3",
  "tschüss": "tschüss.ogg",
  "wie viel": "wie_viel.oga",
  "zwei": "zwei.ogg"
 },
 "el": {
  "Α α": "Α_α.mp3",
  "Β β": "Β_β.mp3",
  "Γ γ": "Γ_γ.mp3",
  "Δ δ": "Δ_δ.mp3",
  "Ε ε": "Ε_ε.mp3",
  "Ελλάδα": "Ελλάδα.mp3",
  "Ζ ζ": "Ζ_ζ.mp3",
  "Η η": "Η_η.mp3",
  "Θ θ": "Θ_θ.mp3",
  "Ι ι": "Ι_ι.mp3",
  "Κ κ": "Κ_κ.mp3",
  "Λ λ": "Λ_λ.mp3",
  "Μ μ": "Μ_μ.mp3",
  "Ν ν": "Ν_ν.mp3",
  "Ξ ξ": "Ξ_ξ.mp3",
  "Ο ο": "Ο_ο.mp3",
  "Π π": "Π_π.mp3",
  "Ρ ρ": "Ρ_ρ.mp3",
  "Σ is written ς at the end of a word — same letter, different tail.": "Σ_is_written_ς_at_the_end_of_a_word_same_letter_different_ta.mp3",
  "Σ σ/ς": "Σ_σ_ς.mp3",
  "Τ τ": "Τ_τ.mp3",
  "Υ υ": "Υ_υ.mp3",
  "Φ φ": "Φ_φ.mp3",
  "Χ χ": "Χ_χ.mp3",
  "Ψ ψ": "Ψ_ψ.mp3",
  "Ω ω": "Ω_ω.mp3",
  "ένα": "ένα.mp3",
  "αι": "αι.mp3",
  "αντίο": "αντίο.mp3",
  "γάτα": "γάτα.mp3",
  "γεια σου": "γεια_σου.mp3",
  "γκ": "γκ.mp3",
  "δάσκαλος": "δάσκαλος.mp3",
  "δεν καταλαβαίνω": "δεν_καταλαβαίνω.mp3",
  "δύο": "δύο.mp3",
  "ει": "ει.mp3",
  "ευχαριστώ": "ευχαριστώ.mp3",
  "καλημέρα": "καλημέρα.mp3",
  "καλησπέρα": "καλησπέρα.mp3",
  "καφές": "καφές.mp3",
  "μπ": "μπ.mp3",
  "ναι": "ναι.mp3",
  "νερό": "νερό.mp3",
  "ντ": "ντ.mp3",
  "νόστιμο": "νόστιμο.mp3",
  "οι": "οι.mp3",
  "ου": "ου.mp3",
  "πέντε": "πέντε.mp3",
  "παρακαλώ": "παρακαλώ.mp3",
  "πόσο κάνει": "πόσο_κάνει.mp3",
  "σκύλος": "σκύλος.mp3",
  "σπίτι": "σπίτι.mp3",
  "συγγνώμη": "συγγνώμη.mp3",
  "σχολείο": "σχολείο.mp3",
  "τέσσερα": "τέσσερα.mp3",
  "τουαλέτα": "τουαλέτα.mp3",
  "τρία": "τρία.mp3",
  "τσ": "τσ.mp3",
  "φίλος": "φίλος.mp3",
  "ψωμί": "ψωμί.mp3",
  "ωραία": "ωραία.mp3",
  "όνομα": "όνομα.mp3",
  "όχι": "όχι.mp3"
 },
 "en": {
  "food": "food.mp3",
  "friend": "friend.mp3",
  "goodbye": "goodbye.mp3",
  "hello": "hello.mp3",
  "how much": "how_much.mp3",
  "love": "love.mp3",
  "no": "no.mp3",
  "one": "one.mp3",
  "please": "please.mp3",
  "sorry": "sorry.mp3",
  "thank you": "thank_you.mp3",
  "three": "three.mp3",
  "toilet": "toilet.mp3",
  "two": "two.mp3",
  "water": "water.mp3",
  "yes": "yes.mp3"
 },
 "eo": {
  "akvo": "akvo.wav",
  "amiko": "amiko.wav",
  "amo": "amo.wav",
  "bonvolu": "bonvolu.wav",
  "dankon": "dankon.wav",
  "du": "du.wav",
  "jes": "jes.wav",
  "kiom": "kiom.wav",
  "manĝaĵo": "manĝaĵo.wav",
  "ne": "ne.wav",
  "necesejo": "necesejo.wav",
  "pardonu": "pardonu.wav",
  "saluton": "saluton.wav",
  "tri": "tri.wav",
  "unu": "unu.wav",
  "ĝis revido": "ĝis_revido.wav"
 },
 "es": {
  "España": "España.mp3",
  "adiós": "adiós.mp3",
  "agua": "agua.mp3",
  "amigo": "amigo.mp3",
  "baño": "baño.mp3",
  "buenos días": "buenos_días.mp3",
  "café": "café.mp3",
  "casa": "casa.mp3",
  "cinco": "cinco.mp3",
  "cuatro": "cuatro.mp3",
  "cuánto cuesta": "cuánto_cuesta.mp3",
  "delicioso": "delicioso.mp3",
  "dos": "dos.mp3",
  "escuela": "escuela.mp3",
  "feliz": "feliz.mp3",
  "gracias": "gracias.mp3",
  "hola": "hola.mp3",
  "lo siento": "lo_siento.mp3",
  "maestro": "maestro.mp3",
  "no": "no.mp3",
  "no entiendo": "no_entiendo.mp3",
  "nombre": "nombre.mp3",
  "pan": "pan.mp3",
  "perro": "perro.mp3",
  "por favor": "por_favor.mp3",
  "sí": "sí.mp3",
  "te quiero": "te_quiero.mp3",
  "tres": "tres.mp3",
  "uno": "uno.mp3"
 },
 "fa": {
  "آب": "آب.mp3",
  "ببخشید": "ببخشید.mp3",
  "بله": "بله.mp3",
  "خداحافظ": "خداحافظ.mp3",
  "دستشویی": "دستشویی.mp3",
  "دو": "دو.mp3",
  "دوست": "دوست.mp3",
  "سلام": "سلام.mp3",
  "سه": "سه.mp3",
  "عشق": "عشق.mp3",
  "غذا": "غذا.mp3",
  "لطفا": "لطفا.mp3",
  "ممنون": "ممنون.mp3",
  "نه": "نه.mp3",
  "چند": "چند.mp3",
  "یک": "یک.mp3"
 },
 "fi": {
  "anteeksi": "anteeksi.mp3",
  "ei": "ei.mp3",
  "hei": "hei.mp3",
  "kaksi": "kaksi.mp3",
  "kiitos": "kiitos.mp3",
  "kolme": "kolme.mp3",
  "kyllä": "kyllä.mp3",
  "näkemiin": "näkemiin.mp3",
  "ole hyvä": "ole_hyvä.mp3",
  "paljonko": "paljonko.mp3",
  "rakkaus": "rakkaus.mp3",
  "ruoka": "ruoka.mp3",
  "vesi": "vesi.mp3",
  "vessa": "vessa.mp3",
  "yksi": "yksi.mp3",
  "ystävä": "ystävä.mp3"
 },
 "fr": {
  "France": "France.mp3",
  "ami": "ami.mp3",
  "au revoir": "au_revoir.mp3",
  "bonjour": "bonjour.mp3",
  "bonsoir": "bonsoir.mp3",
  "café": "café.mp3",
  "chat": "chat.mp3",
  "chien": "chien.mp3",
  "cinq": "cinq.mp3",
  "combien": "combien.mp3",
  "deux": "deux.mp3",
  "délicieux": "délicieux.mp3",
  "eau": "eau.mp3",
  "heureux": "heureux.mp3",
  "ja": "ja.mp3",
  "je ne comprends pas": "je_ne_comprends_pas.mp3",
  "maison": "maison.mp3",
  "merci": "merci.mp3",
  "nom": "nom.mp3",
  "non": "non.mp3",
  "oui": "oui.mp3",
  "pain": "pain.mp3",
  "pardon": "pardon.mp3",
  "professeur": "professeur.mp3",
  "quatre": "quatre.mp3",
  "toilettes": "toilettes.mp3",
  "trois": "trois.mp3",
  "un": "un.mp3",
  "école": "école.mp3"
 },
 "ha": {
  "a'a": "a_a.wav",
  "abinci": "abinci.wav",
  "aboki": "aboki.wav",
  "bayan gida": "bayan_gida.wav",
  "biyu": "biyu.wav",
  "don Allah": "don_Allah.wav",
  "eh": "eh.wav",
  "na gode": "na_gode.wav",
  "nawa": "nawa.wav",
  "ruwa": "ruwa.wav",
  "sai anjima": "sai_anjima.wav",
  "sannu": "sannu.wav",
  "soyayya": "soyayya.wav",
  "uku": "uku.wav",
  "yi hakuri": "yi_hakuri.wav",
  "ɗaya": "ɗaya.wav"
 },
 "he": {
  "אהבה": "אהבה.mp3",
  "אוכל": "אוכל.mp3",
  "אחד": "אחד.mp3",
  "בבקשה": "בבקשה.mp3",
  "חבר": "חבר.mp3",
  "כמה": "כמה.mp3",
  "כן": "כן.mp3",
  "לא": "לא.mp3",
  "להתראות": "להתראות.mp3",
  "מים": "מים.mp3",
  "סליחה": "סליחה.mp3",
  "שירותים": "שירותים.mp3",
  "שלום": "שלום.mp3",
  "שלוש": "שלוש.mp3",
  "שתיים": "שתיים.mp3",
  "תודה": "תודה.mp3"
 },
 "hi": {
  "अ": "अ.mp3",
  "अच्छा": "अच_छ.mp3",
  "आ": "आ.mp3",
  "इ": "इ.mp3",
  "ई": "ई.mp3",
  "उ": "उ.mp3",
  "ऊ": "ऊ.mp3",
  "ए": "ए.mp3",
  "एक": "एक.mp3",
  "ऐ": "ऐ.mp3",
  "ओ": "ओ.mp3",
  "औ": "औ.mp3",
  "क": "क.mp3",
  "क is \"ka\", not \"k\". To get other vowels, add a sign: का ki की कु कू के को.": "क_is_ka_not_k_To_get_other_vowels_add_a_sign_क_ki_क_क_क_क_क.mp3",
  "का": "क.mp3",
  "कि": "क.mp3",
  "कितने का है": "क_तन_क_ह.mp3",
  "की": "क.mp3",
  "कु": "क.mp3",
  "कुत्ता": "क_त_त.mp3",
  "कू": "क.mp3",
  "कृपया": "क_पय.mp3",
  "के": "क.mp3",
  "कै": "क.mp3",
  "को": "क.mp3",
  "कौ": "क.mp3",
  "क्": "क.mp3",
  "ख": "ख.mp3",
  "ग": "ग.mp3",
  "घ": "घ.mp3",
  "घर": "घर.mp3",
  "च": "च.mp3",
  "चाय": "च_य.mp3",
  "चार": "च_र.mp3",
  "चावल": "च_वल.mp3",
  "छ": "छ.mp3",
  "ज": "ज.mp3",
  "झ": "झ.mp3",
  "ट": "ट.mp3",
  "ठ": "ठ.mp3",
  "ड": "ड.mp3",
  "ढ": "ढ.mp3",
  "त": "त.mp3",
  "तीन": "त_न.mp3",
  "थ": "थ.mp3",
  "द": "द.mp3",
  "दो": "द.mp3",
  "दोस्त": "द_स_त.mp3",
  "ध": "ध.mp3",
  "धन्यवाद": "धन_यव_द.mp3",
  "न": "न.mp3",
  "नमस्ते": "नमस_त.mp3",
  "नहीं": "नह.mp3",
  "नाम": "न_म.mp3",
  "प": "प.mp3",
  "पाँच": "प_च.mp3",
  "पानी": "प_न.mp3",
  "प्यार": "प_य_र.mp3",
  "फ": "फ.mp3",
  "फिर मिलेंगे": "फ_र_म_ल_ग.mp3",
  "ब": "ब.mp3",
  "बिल्ली": "ब_ल_ल.mp3",
  "भ": "भ.mp3",
  "भारत": "भ_रत.mp3",
  "म": "म.mp3",
  "माफ़ कीजिए": "म_फ_क_ज_ए.mp3",
  "य": "य.mp3",
  "र": "र.mp3",
  "ल": "ल.mp3",
  "व": "व.mp3",
  "श": "श.mp3",
  "शिक्षक": "श_क_षक.mp3",
  "शौचालय": "श_च_लय.mp3",
  "ष": "ष.mp3",
  "स": "स.mp3",
  "समझ नहीं आया": "समझ_नह_आय.mp3",
  "सुप्रभात": "स_प_रभ_त.mp3",
  "स्कूल": "स_क_ल.mp3",
  "स्वादिष्ट": "स_व_द_ष_ट.mp3",
  "ह": "ह.mp3",
  "हाँ": "ह.mp3"
 },
 "hr": {
  "bok": "bok.mp3",
  "da": "da.mp3",
  "doviđenja": "doviđenja.mp3",
  "dva": "dva.mp3",
  "hrana": "hrana.mp3",
  "hvala": "hvala.mp3",
  "jedan": "jedan.mp3",
  "koliko": "koliko.mp3",
  "ljubav": "ljubav.mp3",
  "molim": "molim.mp3",
  "ne": "ne.mp3",
  "oprostite": "oprostite.mp3",
  "prijatelj": "prijatelj.mp3",
  "tri": "tri.mp3",
  "voda": "voda.mp3",
  "zahod": "zahod.mp3"
 },
 "ht": {
  "bonjou": "bonjou.mp3",
  "de": "de.mp3",
  "dlo": "dlo.mp3",
  "eskize m": "eskize_m.mp3",
  "konbyen": "konbyen.mp3",
  "lanmou": "lanmou.mp3",
  "manje": "manje.mp3",
  "mèsi": "mèsi.mp3",
  "non": "non.mp3",
  "orevwa": "orevwa.mp3",
  "souple": "souple.mp3",
  "twa": "twa.mp3",
  "twalèt": "twalèt.mp3",
  "wi": "wi.mp3",
  "youn": "youn.mp3",
  "zanmi": "zanmi.mp3"
 },
 "hu": {
  "barát": "barát.mp3",
  "bocsánat": "bocsánat.mp3",
  "egy": "egy.mp3",
  "három": "három.mp3",
  "igen": "igen.mp3",
  "kettő": "kettő.mp3",
  "kérem": "kérem.mp3",
  "köszönöm": "köszönöm.mp3",
  "mennyibe": "mennyibe.mp3",
  "mosdó": "mosdó.mp3",
  "nem": "nem.mp3",
  "szerelem": "szerelem.mp3",
  "szia": "szia.mp3",
  "viszlát": "viszlát.mp3",
  "víz": "víz.mp3",
  "étel": "étel.mp3"
 },
 "hy": {
  "այո": "այո.wav",
  "բարև": "բարև.wav",
  "երեք": "երեք.wav",
  "երկու": "երկու.wav",
  "զուգարան": "զուգարան.wav",
  "ընկեր": "ընկեր.wav",
  "ինչքան": "ինչքան.wav",
  "խնդրեմ": "խնդրեմ.wav",
  "մեկ": "մեկ.wav",
  "ներողություն": "ներողություն.wav",
  "շնորհակալություն": "շնորհակալություն.wav",
  "ոչ": "ոչ.wav",
  "ուտելիք": "ուտելիք.wav",
  "ջուր": "ջուր.wav",
  "սեր": "սեր.wav"
 },
 "id": {
  "air": "air.mp3",
  "berapa": "berapa.mp3",
  "cinta": "cinta.mp3",
  "dua": "dua.mp3",
  "halo": "halo.mp3",
  "maaf": "maaf.mp3",
  "makanan": "makanan.mp3",
  "satu": "satu.mp3",
  "selamat tinggal": "selamat_tinggal.mp3",
  "teman": "teman.mp3",
  "terima kasih": "terima_kasih.mp3",
  "tidak": "tidak.mp3",
  "tiga": "tiga.mp3",
  "toilet": "toilet.mp3",
  "tolong": "tolong.mp3",
  "ya": "ya.mp3"
 },
 "it": {
  "acqua": "acqua.mp3",
  "amico": "amico.mp3",
  "amore": "amore.mp3",
  "arrivederci": "arrivederci.mp3",
  "bagno": "bagno.mp3",
  "ciao": "ciao.mp3",
  "cibo": "cibo.mp3",
  "due": "due.mp3",
  "grazie": "grazie.mp3",
  "no": "no.mp3",
  "per favore": "per_favore.mp3",
  "quanto": "quanto.mp3",
  "scusa": "scusa.mp3",
  "sì": "sì.mp3",
  "tre": "tre.mp3",
  "uno": "uno.mp3"
 },
 "ja": {
  "Shapes are angular and made of short, straight strokes.": "Shapes_are_angular_and_made_of_short_straight_strokes.mp3",
  "Strokes always go left to right, top to bottom.": "Strokes_always_go_left_to_right_top_to_bottom.mp3",
  "Write top to bottom, left to right, horizontal before vertical.": "Write_top_to_bottom_left_to_right_horizontal_before_vertical.mp3",
  "あ": "あ.mp3",
  "ありがとう": "ありがとう.mp3",
  "い": "い.mp3",
  "いいえ": "いいえ.mp3",
  "いくらですか": "いくらですか.mp3",
  "いただきます": "いただきます.mp3",
  "う": "う.mp3",
  "え": "え.mp3",
  "お": "お.mp3",
  "おはようございます": "おはようございます.mp3",
  "お茶": "お茶.mp3",
  "お願いします": "お願いします.mp3",
  "か": "か.mp3",
  "が": "が.mp3",
  "き": "き.mp3",
  "ぎ": "ぎ.mp3",
  "く": "く.mp3",
  "ぐ": "ぐ.mp3",
  "け": "け.mp3",
  "げ": "げ.mp3",
  "こ": "こ.mp3",
  "こんにちは": "こんにちは.mp3",
  "こんばんは": "こんばんは.mp3",
  "ご": "ご.mp3",
  "ご飯": "ご飯.mp3",
  "さ": "さ.mp3",
  "さようなら": "さようなら.mp3",
  "ざ": "ざ.mp3",
  "し": "し.mp3",
  "じ": "じ.mp3",
  "す": "す.mp3",
  "すみません": "すみません.mp3",
  "ず": "ず.mp3",
  "せ": "せ.mp3",
  "ぜ": "ぜ.mp3",
  "そ": "そ.mp3",
  "ぞ": "ぞ.mp3",
  "た": "た.mp3",
  "だ": "だ.mp3",
  "ち": "ち.mp3",
  "つ": "つ.mp3",
  "て": "て.mp3",
  "で": "で.mp3",
  "と": "と.mp3",
  "ど": "ど.mp3",
  "な": "な.mp3",
  "に": "に.mp3",
  "ぬ": "ぬ.mp3",
  "ね": "ね.mp3",
  "の": "の.mp3",
  "は": "は.mp3",
  "はい": "はい.mp3",
  "ば": "ば.mp3",
  "ぱ": "ぱ.mp3",
  "ひ": "ひ.mp3",
  "び": "び.mp3",
  "ぴ": "ぴ.mp3",
  "ふ": "ふ.mp3",
  "ぶ": "ぶ.mp3",
  "ぷ": "ぷ.mp3",
  "へ": "へ.mp3",
  "べ": "べ.mp3",
  "ぺ": "ぺ.mp3",
  "ほ": "ほ.mp3",
  "ぼ": "ぼ.mp3",
  "ぽ": "ぽ.mp3",
  "ま": "ま.mp3",
  "またね": "またね.mp3",
  "み": "み.mp3",
  "む": "む.mp3",
  "め": "め.mp3",
  "も": "も.mp3",
  "や": "や.mp3",
  "ゆ": "ゆ.mp3",
  "よ": "よ.mp3",
  "ら": "ら.mp3",
  "り": "り.mp3",
  "る": "る.mp3",
  "れ": "れ.mp3",
  "ろ": "ろ.mp3",
  "わ": "わ.mp3",
  "を": "を.mp3",
  "ん": "ん.mp3",
  "ア": "ア.mp3",
  "イ": "イ.mp3",
  "ウ": "ウ.mp3",
  "エ": "エ.mp3",
  "オ": "オ.mp3",
  "カ": "カ.mp3",
  "キ": "キ.mp3",
  "ク": "ク.mp3",
  "ケ": "ケ.mp3",
  "コ": "コ.mp3",
  "サ": "サ.mp3",
  "シ": "シ.mp3",
  "ス": "ス.mp3",
  "セ": "セ.mp3",
  "ソ": "ソ.mp3",
  "タ": "タ.mp3",
  "チ": "チ.mp3",
  "ツ": "ツ.mp3",
  "テ": "テ.mp3",
  "ト": "ト.mp3",
  "トイレはどこですか": "トイレはどこですか.mp3",
  "ナ": "ナ.mp3",
  "ニ": "ニ.mp3",
  "ヌ": "ヌ.mp3",
  "ネ": "ネ.mp3",
  "ノ": "ノ.mp3",
  "ハ": "ハ.mp3",
  "ヒ": "ヒ.mp3",
  "フ": "フ.mp3",
  "ヘ": "ヘ.mp3",
  "ホ": "ホ.mp3",
  "マ": "マ.mp3",
  "ミ": "ミ.mp3",
  "ム": "ム.mp3",
  "メ": "メ.mp3",
  "モ": "モ.mp3",
  "ヤ": "ヤ.mp3",
  "ユ": "ユ.mp3",
  "ヨ": "ヨ.mp3",
  "ラ": "ラ.mp3",
  "リ": "リ.mp3",
  "ル": "ル.mp3",
  "レ": "レ.mp3",
  "ロ": "ロ.mp3",
  "ワ": "ワ.mp3",
  "ヲ": "ヲ.mp3",
  "ン": "ン.mp3",
  "一": "一.mp3",
  "七": "七.mp3",
  "三": "三.mp3",
  "上": "上.mp3",
  "下": "下.mp3",
  "中": "中.mp3",
  "九": "九.mp3",
  "二": "二.mp3",
  "五": "五.mp3",
  "人": "人.mp3",
  "元気ですか": "元気ですか.mp3",
  "先生": "先生.mp3",
  "八": "八.mp3",
  "六": "六.mp3",
  "分かりません": "分かりません.mp3",
  "十": "十.mp3",
  "友達": "友達.mp3",
  "口": "口.mp3",
  "名前": "名前.mp3",
  "四": "四.mp3",
  "土": "土.mp3",
  "大": "大.mp3",
  "大丈夫": "大丈夫.mp3",
  "学校": "学校.mp3",
  "小": "小.mp3",
  "山": "山.mp3",
  "川": "川.mp3",
  "愛": "愛.mp3",
  "手": "手.mp3",
  "日": "日.mp3",
  "日本": "日本.mp3",
  "月": "月.mp3",
  "木": "木.mp3",
  "本": "本.mp3",
  "楽しい": "楽しい.mp3",
  "水": "水.mp3",
  "火": "火.mp3",
  "犬": "犬.mp3",
  "猫": "猫.mp3",
  "田": "田.mp3",
  "目": "目.mp3",
  "美味しい": "美味しい.mp3",
  "金": "金.mp3",
  "駅": "駅.mp3"
 },
 "ka": {
  "არა": "არა.mp3",
  "ბოდიши": "ბოდიши.mp3",
  "გამარჯობა": "გამარჯობა.mp3",
  "გთხოვთ": "გთხოვთ.mp3",
  "ერთი": "ერთი.mp3",
  "კი": "კი.mp3",
  "მადლობა": "მადლობა.mp3",
  "მეგობარი": "მეგობარი.mp3",
  "ნახვამდის": "ნახვამდის.mp3",
  "ორი": "ორი.mp3",
  "რამდენი": "რამდენი.mp3",
  "სამი": "სამი.mp3",
  "საჭმელი": "საჭმელი.mp3",
  "სიყვარული": "სიყვარული.mp3",
  "ტუალეტი": "ტუალეტი.mp3",
  "წყალი": "წყალი.mp3"
 },
 "ko": {
  "Letters stack into square blocks, one block per syllable: ㅎ+ㅏ+ㄴ = 한.": "Letters_stack_into_square_blocks_one_block_per_syllable_ㅎ_ㅏ_.mp3",
  "감사합니다": "감사합니다.mp3",
  "고양이": "고양이.mp3",
  "괜찮아요": "괜찮아요.mp3",
  "글": "글.mp3",
  "김": "김.mp3",
  "김치": "김치.mp3",
  "네": "네.mp3",
  "넷": "넷.mp3",
  "다섯": "다섯.mp3",
  "둘": "둘.mp3",
  "랑": "랑.mp3",
  "맛있어요": "맛있어요.mp3",
  "몰라요": "몰라요.mp3",
  "물": "물.mp3",
  "밥": "밥.mp3",
  "사": "사.mp3",
  "사랑해요": "사랑해요.mp3",
  "선생님": "선생님.mp3",
  "셋": "셋.mp3",
  "아니요": "아니요.mp3",
  "안녕하세요": "안녕하세요.mp3",
  "안녕히 가세요": "안녕히_가세요.mp3",
  "얼마예요": "얼마예요.mp3",
  "여기": "여기.mp3",
  "이름": "이름.mp3",
  "잘 자요": "잘_자요.mp3",
  "죄송합니다": "죄송합니다.mp3",
  "집": "집.mp3",
  "치": "치.mp3",
  "친구": "친구.mp3",
  "하나": "하나.mp3",
  "학교": "학교.mp3",
  "한": "한.mp3",
  "한국": "한국.mp3",
  "행복해요": "행복해요.mp3",
  "화장실": "화장실.mp3"
 },
 "mn": {
  "баярлалаа": "баярлалаа.mp3",
  "баяртай": "баяртай.mp3",
  "гуйя": "гуйя.mp3",
  "гурав": "гурав.mp3",
  "найз": "найз.mp3",
  "нэг": "нэг.mp3",
  "сайн байна уу": "сайн_байна_уу.mp3",
  "тийм": "тийм.mp3",
  "ус": "ус.mp3",
  "уучлаарай": "уучлаарай.mp3",
  "хайр": "хайр.mp3",
  "хоол": "хоол.mp3",
  "хоёр": "хоёр.mp3",
  "хэд": "хэд.mp3",
  "үгүй": "үгүй.mp3"
 },
 "mr": {
  "एक": "एक.mp3",
  "किती": "क_त.mp3",
  "कृपया": "क_पय.mp3",
  "जेवण": "ज_वण.mp3",
  "तीन": "त_न.mp3",
  "दोन": "द_न.mp3",
  "धन्यवाद": "धन_यव_द.mp3",
  "नमस्कार": "नमस_क_र.mp3",
  "नाही": "न_ह.mp3",
  "पाणी": "प_ण.mp3",
  "प्रेम": "प_र_म.mp3",
  "माफ करा": "म_फ_कर.mp3",
  "मित्र": "म_त_र.mp3",
  "येतो": "य_त.mp3",
  "होय": "ह_य.mp3"
 },
 "ne": {
  "एक": "एक.mp3",
  "कति": "कत.mp3",
  "कृपया": "क_पय.mp3",
  "खाना": "ख_न.mp3",
  "तीन": "त_न.mp3",
  "दुई": "द_ई.mp3",
  "धन्यवाद": "धन_यव_द.mp3",
  "नमस्ते": "नमस_त.mp3",
  "पानी": "प_न.mp3",
  "माफ गर्नुहोस्": "म_फ_गर_न_ह_स.mp3",
  "माया": "म_य.mp3",
  "शौचालय": "श_च_लय.mp3",
  "साथी": "स_थ.mp3",
  "हो": "ह.mp3",
  "होइन": "ह_इन.mp3"
 },
 "nl": {
  "alsjeblieft": "alsjeblieft.mp3",
  "dank je": "dank_je.mp3",
  "doei": "doei.mp3",
  "drie": "drie.mp3",
  "een": "een.mp3",
  "eten": "eten.mp3",
  "hallo": "hallo.mp3",
  "hoeveel": "hoeveel.mp3",
  "ja": "ja.mp3",
  "liefde": "liefde.mp3",
  "nee": "nee.mp3",
  "sorry": "sorry.mp3",
  "toilet": "toilet.mp3",
  "twee": "twee.mp3",
  "vriend": "vriend.mp3",
  "water": "water.mp3"
 },
 "no": {
  "en": "en.mp3",
  "ha det": "ha_det.mp3",
  "hei": "hei.mp3",
  "hvor mye": "hvor_mye.mp3",
  "ja": "ja.mp3",
  "kjærlighet": "kjærlighet.mp3",
  "mat": "mat.mp3",
  "nei": "nei.mp3",
  "takk": "takk.mp3",
  "to": "to.mp3",
  "toalett": "toalett.mp3",
  "tre": "tre.mp3",
  "unnskyld": "unnskyld.mp3",
  "vann": "vann.mp3",
  "venn": "venn.mp3",
  "vær så snill": "vær_så_snill.mp3"
 },
 "pl": {
  "cześć": "cześć.mp3",
  "do widzenia": "do_widzenia.mp3",
  "dwa": "dwa.mp3",
  "dziękuję": "dziękuję.mp3",
  "ile": "ile.mp3",
  "jeden": "jeden.mp3",
  "jedzenie": "jedzenie.mp3",
  "miłość": "miłość.mp3",
  "nie": "nie.mp3",
  "proszę": "proszę.mp3",
  "przepraszam": "przepraszam.mp3",
  "przyjaciel": "przyjaciel.mp3",
  "tak": "tak.mp3",
  "toaleta": "toaleta.mp3",
  "trzy": "trzy.mp3",
  "woda": "woda.mp3"
 },
 "pt": {
  "amigo": "amigo.mp3",
  "amor": "amor.mp3",
  "banheiro": "banheiro.mp3",
  "comida": "comida.mp3",
  "desculpe": "desculpe.mp3",
  "dois": "dois.mp3",
  "não": "não.mp3",
  "obrigado": "obrigado.mp3",
  "olá": "olá.mp3",
  "por favor": "por_favor.mp3",
  "quanto": "quanto.mp3",
  "sim": "sim.mp3",
  "tchau": "tchau.mp3",
  "três": "três.mp3",
  "um": "um.mp3",
  "água": "água.mp3"
 },
 "ro": {
  "apă": "apă.mp3",
  "cât": "cât.mp3",
  "da": "da.mp3",
  "doi": "doi.mp3",
  "dragoste": "dragoste.mp3",
  "la revedere": "la_revedere.mp3",
  "mulțumesc": "mulțumesc.mp3",
  "mâncare": "mâncare.mp3",
  "nu": "nu.mp3",
  "prieten": "prieten.mp3",
  "salut": "salut.mp3",
  "scuze": "scuze.mp3",
  "toaletă": "toaletă.mp3",
  "trei": "trei.mp3",
  "unu": "unu.mp3",
  "vă rog": "vă_rog.mp3"
 },
 "ru": {
  "Watch the false friends: В=v, Н=n, Р=r, С=s, У=u, Х=kh.": "Watch_the_false_friends_В_v_Н_n_Р_r_С_s_У_u_Х_kh.mp3",
  "Ё ё": "Ё_ё.mp3",
  "А а": "А_а.mp3",
  "Б б": "Б_б.mp3",
  "В в": "В_в.mp3",
  "Г г": "Г_г.mp3",
  "Д д": "Д_д.mp3",
  "Е е": "Е_е.mp3",
  "Ж ж": "Ж_ж.mp3",
  "З з": "З_з.mp3",
  "И и": "И_и.mp3",
  "Й й": "Й_й.mp3",
  "К к": "К_к.mp3",
  "Л л": "Л_л.mp3",
  "М м": "М_м.mp3",
  "Н н": "Н_н.mp3",
  "О о": "О_о.mp3",
  "П п": "П_п.mp3",
  "Р р": "Р_р.mp3",
  "Россия": "Россия.ogg",
  "С с": "С_с.mp3",
  "Т т": "Т_т.mp3",
  "У у": "У_у.mp3",
  "Ф ф": "Ф_ф.mp3",
  "Х х": "Х_х.mp3",
  "Ц ц": "Ц_ц.mp3",
  "Ч ч": "Ч_ч.mp3",
  "Ш ш": "Ш_ш.mp3",
  "Щ щ": "Щ_щ.mp3",
  "Ъ ъ": "Ъ_ъ.mp3",
  "Ы ы": "Ы_ы.mp3",
  "Ь ь": "Ь_ь.mp3",
  "Э э": "Э_э.mp3",
  "Ю ю": "Ю_ю.mp3",
  "Я я": "Я_я.mp3",
  "вкусно": "вкусно.mp3",
  "вода": "вода.ogg",
  "вокзал": "вокзал.mp3",
  "да": "да.ogg",
  "два": "два.ogg",
  "до свидания": "до_свидания.mp3",
  "доброе утро": "доброе_утро.wav",
  "дом": "дом.mp3",
  "друг": "друг.mp3",
  "здравствуйте": "здравствуйте.wav",
  "извините": "извините.mp3",
  "имя": "имя.mp3",
  "нет": "нет.mp3",
  "один": "один.mp3",
  "пожалуйста": "пожалуйста.mp3",
  "привет": "привет.wav",
  "пять": "пять.mp3",
  "сколько стоит": "сколько_стоит.mp3",
  "собака": "собака.mp3",
  "спасибо": "спасибо.mp3",
  "три": "три.mp3",
  "туалет": "туалет.mp3",
  "учитель": "учитель.mp3",
  "хлеб": "хлеб.mp3",
  "хорошо": "хорошо.mp3",
  "чай": "чай.mp3",
  "четыре": "четыре.mp3",
  "школа": "школа.mp3",
  "я не понимаю": "я_не_понимаю.mp3",
  "я тебя люблю": "я_тебя_люблю.mp3"
 },
 "sk": {
  "ahoj": "ahoj.mp3",
  "dovidenia": "dovidenia.mp3",
  "dva": "dva.mp3",
  "jeden": "jeden.mp3",
  "jedlo": "jedlo.mp3",
  "koľko": "koľko.mp3",
  "láska": "láska.mp3",
  "nie": "nie.mp3",
  "prepáčte": "prepáčte.mp3",
  "priateľ": "priateľ.mp3",
  "prosím": "prosím.mp3",
  "tri": "tri.mp3",
  "voda": "voda.mp3",
  "záchod": "záchod.mp3",
  "áno": "áno.mp3",
  "ďakujem": "ďakujem.mp3"
 },
 "so": {
  "biyo": "biyo.mp3",
  "cunto": "cunto.mp3",
  "fadlan": "fadlan.mp3",
  "haa": "haa.mp3",
  "immisa": "immisa.mp3",
  "jacayl": "jacayl.mp3",
  "kow": "kow.mp3",
  "laba": "laba.mp3",
  "mahadsanid": "mahadsanid.mp3",
  "maya": "maya.mp3",
  "musqul": "musqul.mp3",
  "nabadgelyo": "nabadgelyo.mp3",
  "raali ahow": "raali_ahow.mp3",
  "saaxiib": "saaxiib.mp3",
  "saddex": "saddex.mp3",
  "salaan": "salaan.mp3"
 },
 "sq": {
  "banjo": "banjo.mp3",
  "dashuri": "dashuri.mp3",
  "dy": "dy.mp3",
  "faleminderit": "faleminderit.mp3",
  "jo": "jo.mp3",
  "ju lutem": "ju_lutem.mp3",
  "mik": "mik.mp3",
  "mirupafshim": "mirupafshim.mp3",
  "më fal": "më_fal.mp3",
  "një": "një.mp3",
  "po": "po.mp3",
  "përshëndetje": "përshëndetje.mp3",
  "sa": "sa.mp3",
  "tre": "tre.mp3",
  "ujë": "ujë.mp3",
  "ushqim": "ushqim.mp3"
 },
 "sr": {
  "вода": "вода.mp3",
  "да": "да.mp3",
  "два": "два.mp3",
  "довиђења": "довиђења.mp3",
  "здраво": "здраво.mp3",
  "извините": "извините.mp3",
  "колико": "колико.mp3",
  "молим": "молим.mp3",
  "не": "не.mp3",
  "пријатељ": "пријатељ.mp3",
  "тоалет": "тоалет.mp3",
  "три": "три.mp3",
  "хвала": "хвала.mp3",
  "храна": "храна.mp3",
  "један": "један.mp3",
  "љубав": "љубав.mp3"
 },
 "sv": {
  "ett": "ett.mp3",
  "förlåt": "förlåt.mp3",
  "hej": "hej.mp3",
  "hej då": "hej_då.mp3",
  "hur mycket": "hur_mycket.mp3",
  "ja": "ja.mp3",
  "kärlek": "kärlek.mp3",
  "mat": "mat.mp3",
  "nej": "nej.mp3",
  "snälla": "snälla.mp3",
  "tack": "tack.mp3",
  "toalett": "toalett.mp3",
  "tre": "tre.mp3",
  "två": "två.mp3",
  "vatten": "vatten.mp3",
  "vän": "vän.mp3"
 },
 "sw": {
  "asante": "asante.flac",
  "bei gani": "bei_gani.mp3",
  "chakula": "chakula.flac",
  "choo": "choo.mp3",
  "hapana": "hapana.mp3",
  "jambo": "jambo.mp3",
  "kwaheri": "kwaheri.mp3",
  "maji": "maji.mp3",
  "mbili": "mbili.mp3",
  "moja": "moja.mp3",
  "ndiyo": "ndiyo.mp3",
  "rafiki": "rafiki.mp3",
  "samahani": "samahani.mp3",
  "tafadhali": "tafadhali.mp3",
  "tatu": "tatu.mp3",
  "upendo": "upendo.mp3"
 },
 "ta": {
  "அன்பு": "அன_ப.mp3",
  "ஆம்": "ஆம.mp3",
  "இரண்டு": "இரண_ட.mp3",
  "இல்லை": "இல_ல.mp3",
  "உணவு": "உணவ.mp3",
  "எவ்வளவு": "எவ_வளவ.mp3",
  "ஒன்று": "ஒன_ற.mp3",
  "தண்ணீர்": "தண_ண_ர.mp3",
  "தயவுசெய்து": "தயவ_ச_ய_த.mp3",
  "நண்பன்": "நண_பன.mp3",
  "நன்றி": "நன_ற.mp3",
  "மன்னிக்கவும்": "மன_ன_க_கவ_ம.mp3",
  "மூன்று": "ம_ன_ற.mp3",
  "வணக்கம்": "வணக_கம.mp3"
 },
 "th": {
  "กรุณา": "กร_ณา.mp3",
  "ขอบคุณ": "ขอบค_ณ.mp3",
  "ขอโทษ": "ขอโทษ.mp3",
  "ความรัก": "ความร_ก.mp3",
  "น้ำ": "น_ำ.mp3",
  "ลาก่อน": "ลาก_อน.mp3",
  "สวัสดี": "สว_สด.mp3",
  "สอง": "สอง.mp3",
  "สาม": "สาม.mp3",
  "หนึ่ง": "หน_ง.mp3",
  "ห้องน้ำ": "ห_องน_ำ.mp3",
  "อาหาร": "อาหาร.mp3",
  "เท่าไร": "เท_าไร.mp3",
  "เพื่อน": "เพ_อน.mp3",
  "ใช่": "ใช.mp3",
  "ไม่": "ไม.mp3"
 },
 "tl": {
  "banyo": "banyo.mp3",
  "dalawa": "dalawa.mp3",
  "hindi": "hindi.mp3",
  "isa": "isa.mp3",
  "kaibigan": "kaibigan.mp3",
  "kumusta": "kumusta.mp3",
  "magkano": "magkano.mp3",
  "oo": "oo.mp3",
  "paalam": "paalam.mp3",
  "pag-ibig": "pag_ibig.mp3",
  "pagkain": "pagkain.mp3",
  "pakiusap": "pakiusap.mp3",
  "pasensya": "pasensya.mp3",
  "salamat": "salamat.mp3",
  "tatlo": "tatlo.mp3",
  "tubig": "tubig.mp3"
 },
 "tr": {
  "affedersiniz": "affedersiniz.mp3",
  "arkadaş": "arkadaş.mp3",
  "aşk": "aşk.mp3",
  "bir": "bir.mp3",
  "evet": "evet.mp3",
  "hayır": "hayır.mp3",
  "hoşça kal": "hoşça_kal.mp3",
  "iki": "iki.mp3",
  "lütfen": "lütfen.mp3",
  "merhaba": "merhaba.mp3",
  "ne kadar": "ne_kadar.mp3",
  "su": "su.mp3",
  "teşekkürler": "teşekkürler.mp3",
  "tuvalet": "tuvalet.mp3",
  "yemek": "yemek.mp3",
  "üç": "üç.mp3"
 },
 "uk": {
  "будь ласка": "будь_ласка.mp3",
  "вибачте": "вибачте.mp3",
  "вода": "вода.mp3",
  "два": "два.mp3",
  "до побачення": "до_побачення.mp3",
  "друг": "друг.mp3",
  "дякую": "дякую.mp3",
  "любов": "любов.mp3",
  "ні": "ні.mp3",
  "один": "один.mp3",
  "привіт": "привіт.mp3",
  "скільки": "скільки.mp3",
  "так": "так.mp3",
  "три": "три.mp3",
  "туалет": "туалет.mp3",
  "їжа": "їжа.mp3"
 },
 "ur": {
  "السلام علیکم": "السلام_علیکم.mp3",
  "ایک": "ایک.mp3",
  "باتھ روم": "باتھ_روم.mp3",
  "تین": "تین.mp3",
  "خدا حافظ": "خدا_حافظ.mp3",
  "دو": "دو.mp3",
  "دوست": "دوست.mp3",
  "شکریہ": "شکریہ.mp3",
  "محبت": "محبت.mp3",
  "معاف کیجیے": "معاف_کیجیے.mp3",
  "مہربانی": "مہربانی.mp3",
  "نہیں": "نہیں.mp3",
  "پانی": "پانی.mp3",
  "کتنا": "کتنا.mp3",
  "کھانا": "کھانا.mp3",
  "ہاں": "ہاں.mp3"
 },
 "vi": {
  "ba": "ba.mp3",
  "bao nhiêu": "bao_nhiêu.mp3",
  "bạn": "bạn.mp3",
  "cảm ơn": "cảm_ơn.mp3",
  "hai": "hai.mp3",
  "không": "không.mp3",
  "làm ơn": "làm_ơn.mp3",
  "một": "một.mp3",
  "nhà vệ sinh": "nhà_vệ_sinh.mp3",
  "nước": "nước.mp3",
  "thức ăn": "thức_ăn.mp3",
  "tình yêu": "tình_yêu.mp3",
  "tạm biệt": "tạm_biệt.mp3",
  "vâng": "vâng.mp3",
  "xin chào": "xin_chào.mp3",
  "xin lỗi": "xin_lỗi.mp3"
 },
 "yo": {
  "báwo ni": "báwo_ni.wav",
  "bẹ́ẹ̀ ni": "bẹ_ẹ_ni.wav",
  "e ṣé": "e_ṣé.wav",
  "jọ̀wọ́": "jọ_wọ.wav",
  "mà bínú": "mà_bínú.wav",
  "mélòó": "mélòó.wav",
  "omi": "omi.wav",
  "oúnjẹ": "oúnjẹ.wav",
  "rárá": "rárá.wav",
  "èjì": "èjì.wav",
  "ìfẹ́": "ìfẹ.wav",
  "ó dàbọ̀": "ó_dàbọ.wav",
  "ẹ̀ta": "ẹ_ta.wav",
  "ọ̀kan": "ọ_kan.wav",
  "ọ̀rẹ́": "ọ_rẹ.wav"
 },
 "zh": {
  "-i (after zh ch sh r z c s)": "i_after_zh_ch_sh_r_z_c_s.mp3",
  "Stroke order: top to bottom, left to right, horizontal before vertical.": "Stroke_order_top_to_bottom_left_to_right_horizontal_before_v.mp3",
  "The tone mark sits on the vowel: mā má mǎ mà are four different words.": "The_tone_mark_sits_on_the_vowel_mā_má_mǎ_mà_are_four_differe.mp3",
  "b": "b.mp3",
  "c": "c.mp3",
  "ch": "ch.mp3",
  "e": "e.mp3",
  "hiragana": "hiragana.mp3",
  "ian": "ian.mp3",
  "iu": "iu.mp3",
  "j": "j.mp3",
  "ma 吗": "ma_吗.mp3",
  "mà 骂": "mà_骂.mp3",
  "má 麻": "má_麻.mp3",
  "mā 妈": "mā_妈.mp3",
  "mǎ 马": "mǎ_马.mp3",
  "ong": "ong.mp3",
  "p": "p.mp3",
  "q": "q.mp3",
  "r": "r.mp3",
  "sh": "sh.mp3",
  "ui": "ui.mp3",
  "x": "x.mp3",
  "z": "z.mp3",
  "zh": "zh.mp3",
  "ü": "ü.mp3",
  "一": "一.mp3",
  "七": "七.mp3",
  "三": "三.mp3",
  "不客气": "不客气.mp3",
  "不是": "不是.mp3",
  "中": "中.mp3",
  "中国": "中国.mp3",
  "九": "九.mp3",
  "二": "二.mp3",
  "五": "五.mp3",
  "人": "人.mp3",
  "你好": "你好.mp3",
  "八": "八.mp3",
  "六": "六.mp3",
  "再见": "再见.mp3",
  "十": "十.mp3",
  "名字": "名字.mp3",
  "四": "四.mp3",
  "国": "国.mp3",
  "多少钱": "多少钱.mp3",
  "大": "大.mp3",
  "好": "好.mp3",
  "好吃": "好吃.mp3",
  "学校": "学校.mp3",
  "对不起": "对不起.mp3",
  "小": "小.mp3",
  "山": "山.mp3",
  "很高兴": "很高兴.mp3",
  "我": "我.mp3",
  "我不懂": "我不懂.mp3",
  "我爱你": "我爱你.mp3",
  "日": "日.mp3",
  "早上好": "早上好.mp3",
  "是": "是.mp3",
  "月": "月.mp3",
  "朋友": "朋友.mp3",
  "水": "水.mp3",
  "洗手间": "洗手间.mp3",
  "火": "火.mp3",
  "火车站": "火车站.mp3",
  "狗": "狗.mp3",
  "猫": "猫.mp3",
  "米饭": "米饭.mp3",
  "老师": "老师.mp3",
  "茶": "茶.mp3",
  "谢谢": "谢谢.mp3"
 },
 "zu": {
  "amanzi": "amanzi.mp3",
  "kubili": "kubili.mp3",
  "kunye": "kunye.mp3",
  "kuthathu": "kuthathu.mp3",
  "malini": "malini.mp3",
  "ngicela": "ngicela.mp3",
  "ngiyabonga": "ngiyabonga.mp3",
  "sala kahle": "sala_kahle.mp3",
  "sawubona": "sawubona.mp3",
  "ukudla": "ukudla.mp3",
  "umngane": "umngane.mp3",
  "uthando": "uthando.mp3",
  "uxolo": "uxolo.mp3",
  "yebo": "yebo.mp3"
 }
};
window.RECORDINGS_SOURCE = {
 "af": {
  "asseblief": "made",
  "dankie": "made",
  "drie": "made",
  "een": "made",
  "hallo": "made",
  "hoeveel": "made",
  "ja": "made",
  "jammer": "made",
  "kos": "made",
  "liefde": "made",
  "nee": "made",
  "toilet": "made",
  "totsiens": "made",
  "twee": "made",
  "vriend": "made",
  "water": "made"
 },
 "am": {
  "ሁለት": "made",
  "ምግብ": "made",
  "ሰላም": "made",
  "ስንት": "made",
  "ሶስት": "made",
  "አመሰግናለሁ": "made",
  "አንድ": "made",
  "አዎ": "made",
  "አይደለም": "made",
  "እባክህ": "made",
  "ውሃ": "made",
  "ይቅርታ": "made",
  "ደህና ሁን": "made",
  "ጓደኛ": "made",
  "ፍቅር": "made"
 },
 "ar": {
  "Six letters (ا د ذ ر ز و) never join to the left — the word breaks after them.": "made",
  "آسف": "made",
  "أحبك": "made",
  "أربعة": "made",
  "ا": "made",
  "اثنان": "made",
  "اسم": "made",
  "السلام عليكم": "made",
  "ب": "made",
  "بـ": "made",
  "بيت": "made",
  "بَ": "made",
  "بُ": "made",
  "بِ": "made",
  "بّ": "made",
  "بْ": "made",
  "ت": "made",
  "ث": "made",
  "ثلاثة": "made",
  "ج": "made",
  "جميل": "made",
  "ح": "made",
  "حمام": "made",
  "خ": "made",
  "خبز": "made",
  "خمسة": "made",
  "د": "made",
  "ذ": "made",
  "ر": "made",
  "ز": "made",
  "س": "made",
  "ش": "made",
  "شاي": "made",
  "شكرا": "made",
  "ص": "made",
  "صباح الخير": "made",
  "صديق": "made",
  "ض": "made",
  "ط": "made",
  "ظ": "made",
  "ع": "made",
  "غ": "made",
  "ـب": "made",
  "ـبـ": "made",
  "ف": "made",
  "ق": "made",
  "قطة": "made",
  "ك": "made",
  "كم الثمن": "made",
  "ل": "made",
  "لا": "made",
  "لا أفهم": "made",
  "لذيذ": "made",
  "م": "made",
  "مدرسة": "made",
  "مرحبا": "made",
  "مصر": "made",
  "مع السلامة": "made",
  "معلم": "made",
  "من فضلك": "made",
  "ن": "made",
  "نعم": "made",
  "ه": "made",
  "و": "made",
  "واحد": "made",
  "ي": "made"
 },
 "bg": {
  "благодаря": "made",
  "вода": "made",
  "да": "made",
  "две": "made",
  "довиждане": "made",
  "едно": "made",
  "здравей": "made",
  "извинете": "made",
  "колко": "made",
  "любов": "made",
  "моля": "made",
  "не": "made",
  "приятел": "made",
  "тоалетна": "made",
  "три": "made",
  "храна": "made"
 },
 "bn": {
  "এক": "made",
  "কত": "made",
  "খাবার": "made",
  "জল": "made",
  "তিন": "made",
  "দয়া করে": "made",
  "দুঃখিত": "made",
  "দুই": "made",
  "ধন্যবাদ": "made",
  "নমস্কার": "made",
  "না": "made",
  "বন্ধু": "made",
  "বাথরুম": "made",
  "বিদায়": "made",
  "ভালোবাসা": "made",
  "হ্যাঁ": "made"
 },
 "ca": {
  "adéu": "made",
  "aigua": "made",
  "amic": "made",
  "amor": "made",
  "dos": "made",
  "gràcies": "made",
  "hola": "made",
  "lavabo": "made",
  "menjar": "made",
  "no": "made",
  "perdó": "made",
  "quant": "made",
  "si us plau": "made",
  "sí": "made",
  "tres": "made",
  "un": "made"
 },
 "cs": {
  "ahoj": "made",
  "ano": "made",
  "dva": "made",
  "děkuji": "made",
  "jeden": "made",
  "jídlo": "made",
  "kolik": "made",
  "láska": "made",
  "na shledanou": "made",
  "ne": "made",
  "promiňte": "made",
  "prosím": "made",
  "přítel": "made",
  "tři": "made",
  "voda": "made",
  "záchod": "made"
 },
 "da": {
  "en": "made",
  "farvel": "made",
  "hej": "made",
  "hvor meget": "made",
  "ja": "made",
  "kærlighed": "made",
  "mad": "made",
  "nej": "made",
  "tak": "made",
  "to": "made",
  "toilet": "made",
  "tre": "made",
  "undskyld": "made",
  "vand": "made",
  "ven": "made",
  "vær så god": "made"
 },
 "de": {
  "Essen": "human",
  "Freund": "human",
  "Liebe": "human",
  "Toilette": "human",
  "Wasser": "human",
  "bitte": "human",
  "danke": "human",
  "drei": "made",
  "eins": "human",
  "entschuldigung": "made",
  "hallo": "human",
  "ja": "human",
  "nein": "made",
  "tschüss": "human",
  "wie viel": "human",
  "zwei": "human"
 },
 "el": {
  "Α α": "made",
  "Β β": "made",
  "Γ γ": "made",
  "Δ δ": "made",
  "Ε ε": "made",
  "Ελλάδα": "made",
  "Ζ ζ": "made",
  "Η η": "made",
  "Θ θ": "made",
  "Ι ι": "made",
  "Κ κ": "made",
  "Λ λ": "made",
  "Μ μ": "made",
  "Ν ν": "made",
  "Ξ ξ": "made",
  "Ο ο": "made",
  "Π π": "made",
  "Ρ ρ": "made",
  "Σ is written ς at the end of a word — same letter, different tail.": "made",
  "Σ σ/ς": "made",
  "Τ τ": "made",
  "Υ υ": "made",
  "Φ φ": "made",
  "Χ χ": "made",
  "Ψ ψ": "made",
  "Ω ω": "made",
  "ένα": "made",
  "αι": "made",
  "αντίο": "made",
  "γάτα": "made",
  "γεια σου": "made",
  "γκ": "made",
  "δάσκαλος": "made",
  "δεν καταλαβαίνω": "made",
  "δύο": "made",
  "ει": "made",
  "ευχαριστώ": "made",
  "καλημέρα": "made",
  "καλησπέρα": "made",
  "καφές": "made",
  "μπ": "made",
  "ναι": "made",
  "νερό": "made",
  "ντ": "made",
  "νόστιμο": "made",
  "οι": "made",
  "ου": "made",
  "πέντε": "made",
  "παρακαλώ": "made",
  "πόσο κάνει": "made",
  "σκύλος": "made",
  "σπίτι": "made",
  "συγγνώμη": "made",
  "σχολείο": "made",
  "τέσσερα": "made",
  "τουαλέτα": "made",
  "τρία": "made",
  "τσ": "made",
  "φίλος": "made",
  "ψωμί": "made",
  "ωραία": "made",
  "όνομα": "made",
  "όχι": "made"
 },
 "en": {
  "food": "made",
  "friend": "made",
  "goodbye": "made",
  "hello": "made",
  "how much": "made",
  "love": "made",
  "no": "made",
  "one": "made",
  "please": "made",
  "sorry": "made",
  "thank you": "made",
  "three": "made",
  "toilet": "made",
  "two": "made",
  "water": "made",
  "yes": "made"
 },
 "eo": {
  "akvo": "made",
  "amiko": "made",
  "amo": "made",
  "bonvolu": "made",
  "dankon": "made",
  "du": "made",
  "jes": "made",
  "kiom": "made",
  "manĝaĵo": "made",
  "ne": "made",
  "necesejo": "made",
  "pardonu": "made",
  "saluton": "made",
  "tri": "made",
  "unu": "made",
  "ĝis revido": "made"
 },
 "es": {
  "España": "made",
  "adiós": "made",
  "agua": "made",
  "amigo": "made",
  "baño": "made",
  "buenos días": "made",
  "café": "made",
  "casa": "made",
  "cinco": "made",
  "cuatro": "made",
  "cuánto cuesta": "made",
  "delicioso": "made",
  "dos": "made",
  "escuela": "made",
  "feliz": "made",
  "gracias": "made",
  "hola": "made",
  "lo siento": "made",
  "maestro": "made",
  "no": "made",
  "no entiendo": "made",
  "nombre": "made",
  "pan": "made",
  "perro": "made",
  "por favor": "made",
  "sí": "made",
  "te quiero": "made",
  "tres": "made",
  "uno": "made"
 },
 "fa": {
  "آب": "made",
  "ببخشید": "made",
  "بله": "made",
  "خداحافظ": "made",
  "دستشویی": "made",
  "دو": "made",
  "دوست": "made",
  "سلام": "made",
  "سه": "made",
  "عشق": "made",
  "غذا": "made",
  "لطفا": "made",
  "ممنون": "made",
  "نه": "made",
  "چند": "made",
  "یک": "made"
 },
 "fi": {
  "anteeksi": "made",
  "ei": "made",
  "hei": "made",
  "kaksi": "made",
  "kiitos": "made",
  "kolme": "made",
  "kyllä": "made",
  "näkemiin": "made",
  "ole hyvä": "made",
  "paljonko": "made",
  "rakkaus": "made",
  "ruoka": "made",
  "vesi": "made",
  "vessa": "made",
  "yksi": "made",
  "ystävä": "made"
 },
 "fr": {
  "France": "made",
  "ami": "made",
  "au revoir": "made",
  "bonjour": "made",
  "bonsoir": "made",
  "café": "made",
  "chat": "made",
  "chien": "made",
  "cinq": "made",
  "combien": "made",
  "deux": "made",
  "délicieux": "made",
  "eau": "made",
  "heureux": "made",
  "ja": "made",
  "je ne comprends pas": "made",
  "maison": "made",
  "merci": "made",
  "nom": "made",
  "non": "made",
  "oui": "made",
  "pain": "made",
  "pardon": "made",
  "professeur": "made",
  "quatre": "made",
  "toilettes": "made",
  "trois": "made",
  "un": "made",
  "école": "made"
 },
 "ha": {
  "a'a": "made",
  "abinci": "made",
  "aboki": "made",
  "bayan gida": "made",
  "biyu": "made",
  "don Allah": "made",
  "eh": "made",
  "na gode": "made",
  "nawa": "made",
  "ruwa": "made",
  "sai anjima": "made",
  "sannu": "made",
  "soyayya": "made",
  "uku": "made",
  "yi hakuri": "made",
  "ɗaya": "made"
 },
 "he": {
  "אהבה": "made",
  "אוכל": "made",
  "אחד": "made",
  "בבקשה": "made",
  "חבר": "made",
  "כמה": "made",
  "כן": "made",
  "לא": "made",
  "להתראות": "made",
  "מים": "made",
  "סליחה": "made",
  "שירותים": "made",
  "שלום": "made",
  "שלוש": "made",
  "שתיים": "made",
  "תודה": "made"
 },
 "hi": {
  "अ": "made",
  "अच्छा": "made",
  "आ": "made",
  "इ": "made",
  "ई": "made",
  "उ": "made",
  "ऊ": "made",
  "ए": "made",
  "एक": "made",
  "ऐ": "made",
  "ओ": "made",
  "औ": "made",
  "क": "made",
  "क is \"ka\", not \"k\". To get other vowels, add a sign: का ki की कु कू के को.": "made",
  "का": "made",
  "कि": "made",
  "कितने का है": "made",
  "की": "made",
  "कु": "made",
  "कुत्ता": "made",
  "कू": "made",
  "कृपया": "made",
  "के": "made",
  "कै": "made",
  "को": "made",
  "कौ": "made",
  "क्": "made",
  "ख": "made",
  "ग": "made",
  "घ": "made",
  "घर": "made",
  "च": "made",
  "चाय": "made",
  "चार": "made",
  "चावल": "made",
  "छ": "made",
  "ज": "made",
  "झ": "made",
  "ट": "made",
  "ठ": "made",
  "ड": "made",
  "ढ": "made",
  "त": "made",
  "तीन": "made",
  "थ": "made",
  "द": "made",
  "दो": "made",
  "दोस्त": "made",
  "ध": "made",
  "धन्यवाद": "made",
  "न": "made",
  "नमस्ते": "made",
  "नहीं": "made",
  "नाम": "made",
  "प": "made",
  "पाँच": "made",
  "पानी": "made",
  "प्यार": "made",
  "फ": "made",
  "फिर मिलेंगे": "made",
  "ब": "made",
  "बिल्ली": "made",
  "भ": "made",
  "भारत": "made",
  "म": "made",
  "माफ़ कीजिए": "made",
  "य": "made",
  "र": "made",
  "ल": "made",
  "व": "made",
  "श": "made",
  "शिक्षक": "made",
  "शौचालय": "made",
  "ष": "made",
  "स": "made",
  "समझ नहीं आया": "made",
  "सुप्रभात": "made",
  "स्कूल": "made",
  "स्वादिष्ट": "made",
  "ह": "made",
  "हाँ": "made"
 },
 "hr": {
  "bok": "made",
  "da": "made",
  "doviđenja": "made",
  "dva": "made",
  "hrana": "made",
  "hvala": "made",
  "jedan": "made",
  "koliko": "made",
  "ljubav": "made",
  "molim": "made",
  "ne": "made",
  "oprostite": "made",
  "prijatelj": "made",
  "tri": "made",
  "voda": "made",
  "zahod": "made"
 },
 "ht": {
  "bonjou": "made",
  "de": "made",
  "dlo": "made",
  "eskize m": "made",
  "konbyen": "made",
  "lanmou": "made",
  "manje": "made",
  "mèsi": "made",
  "non": "made",
  "orevwa": "made",
  "souple": "made",
  "twa": "made",
  "twalèt": "made",
  "wi": "made",
  "youn": "made",
  "zanmi": "made"
 },
 "hu": {
  "barát": "made",
  "bocsánat": "made",
  "egy": "made",
  "három": "made",
  "igen": "made",
  "kettő": "made",
  "kérem": "made",
  "köszönöm": "made",
  "mennyibe": "made",
  "mosdó": "made",
  "nem": "made",
  "szerelem": "made",
  "szia": "made",
  "viszlát": "made",
  "víz": "made",
  "étel": "made"
 },
 "hy": {
  "այո": "made",
  "բարև": "made",
  "երեք": "made",
  "երկու": "made",
  "զուգարան": "made",
  "ընկեր": "made",
  "ինչքան": "made",
  "խնդրեմ": "made",
  "մեկ": "made",
  "ներողություն": "made",
  "շնորհակալություն": "made",
  "ոչ": "made",
  "ուտելիք": "made",
  "ջուր": "made",
  "սեր": "made"
 },
 "id": {
  "air": "made",
  "berapa": "made",
  "cinta": "made",
  "dua": "made",
  "halo": "made",
  "maaf": "made",
  "makanan": "made",
  "satu": "made",
  "selamat tinggal": "made",
  "teman": "made",
  "terima kasih": "made",
  "tidak": "made",
  "tiga": "made",
  "toilet": "made",
  "tolong": "made",
  "ya": "made"
 },
 "it": {
  "acqua": "made",
  "amico": "made",
  "amore": "made",
  "arrivederci": "made",
  "bagno": "made",
  "ciao": "made",
  "cibo": "made",
  "due": "made",
  "grazie": "made",
  "no": "made",
  "per favore": "made",
  "quanto": "made",
  "scusa": "made",
  "sì": "made",
  "tre": "made",
  "uno": "made"
 },
 "ja": {
  "Shapes are angular and made of short, straight strokes.": "made",
  "Strokes always go left to right, top to bottom.": "made",
  "Write top to bottom, left to right, horizontal before vertical.": "made",
  "あ": "made",
  "ありがとう": "made",
  "い": "made",
  "いいえ": "made",
  "いくらですか": "made",
  "いただきます": "made",
  "う": "made",
  "え": "made",
  "お": "made",
  "おはようございます": "made",
  "お茶": "made",
  "お願いします": "made",
  "か": "made",
  "が": "made",
  "き": "made",
  "ぎ": "made",
  "く": "made",
  "ぐ": "made",
  "け": "made",
  "げ": "made",
  "こ": "made",
  "こんにちは": "made",
  "こんばんは": "made",
  "ご": "made",
  "ご飯": "made",
  "さ": "made",
  "さようなら": "made",
  "ざ": "made",
  "し": "made",
  "じ": "made",
  "す": "made",
  "すみません": "made",
  "ず": "made",
  "せ": "made",
  "ぜ": "made",
  "そ": "made",
  "ぞ": "made",
  "た": "made",
  "だ": "made",
  "ち": "made",
  "つ": "made",
  "て": "made",
  "で": "made",
  "と": "made",
  "ど": "made",
  "な": "made",
  "に": "made",
  "ぬ": "made",
  "ね": "made",
  "の": "made",
  "は": "made",
  "はい": "made",
  "ば": "made",
  "ぱ": "made",
  "ひ": "made",
  "び": "made",
  "ぴ": "made",
  "ふ": "made",
  "ぶ": "made",
  "ぷ": "made",
  "へ": "made",
  "べ": "made",
  "ぺ": "made",
  "ほ": "made",
  "ぼ": "made",
  "ぽ": "made",
  "ま": "made",
  "またね": "made",
  "み": "made",
  "む": "made",
  "め": "made",
  "も": "made",
  "や": "made",
  "ゆ": "made",
  "よ": "made",
  "ら": "made",
  "り": "made",
  "る": "made",
  "れ": "made",
  "ろ": "made",
  "わ": "made",
  "を": "made",
  "ん": "made",
  "ア": "made",
  "イ": "made",
  "ウ": "made",
  "エ": "made",
  "オ": "made",
  "カ": "made",
  "キ": "made",
  "ク": "made",
  "ケ": "made",
  "コ": "made",
  "サ": "made",
  "シ": "made",
  "ス": "made",
  "セ": "made",
  "ソ": "made",
  "タ": "made",
  "チ": "made",
  "ツ": "made",
  "テ": "made",
  "ト": "made",
  "トイレはどこですか": "made",
  "ナ": "made",
  "ニ": "made",
  "ヌ": "made",
  "ネ": "made",
  "ノ": "made",
  "ハ": "made",
  "ヒ": "made",
  "フ": "made",
  "ヘ": "made",
  "ホ": "made",
  "マ": "made",
  "ミ": "made",
  "ム": "made",
  "メ": "made",
  "モ": "made",
  "ヤ": "made",
  "ユ": "made",
  "ヨ": "made",
  "ラ": "made",
  "リ": "made",
  "ル": "made",
  "レ": "made",
  "ロ": "made",
  "ワ": "made",
  "ヲ": "made",
  "ン": "made",
  "一": "made",
  "七": "made",
  "三": "made",
  "上": "made",
  "下": "made",
  "中": "made",
  "九": "made",
  "二": "made",
  "五": "made",
  "人": "made",
  "元気ですか": "made",
  "先生": "made",
  "八": "made",
  "六": "made",
  "分かりません": "made",
  "十": "made",
  "友達": "made",
  "口": "made",
  "名前": "made",
  "四": "made",
  "土": "made",
  "大": "made",
  "大丈夫": "made",
  "学校": "made",
  "小": "made",
  "山": "made",
  "川": "made",
  "愛": "made",
  "手": "made",
  "日": "made",
  "日本": "made",
  "月": "made",
  "木": "made",
  "本": "made",
  "楽しい": "made",
  "水": "made",
  "火": "made",
  "犬": "made",
  "猫": "made",
  "田": "made",
  "目": "made",
  "美味しい": "made",
  "金": "made",
  "駅": "made"
 },
 "ka": {
  "არა": "made",
  "ბოდიши": "made",
  "გამარჯობა": "made",
  "გთხოვთ": "made",
  "ერთი": "made",
  "კი": "made",
  "მადლობა": "made",
  "მეგობარი": "made",
  "ნახვამდის": "made",
  "ორი": "made",
  "რამდენი": "made",
  "სამი": "made",
  "საჭმელი": "made",
  "სიყვარული": "made",
  "ტუალეტი": "made",
  "წყალი": "made"
 },
 "ko": {
  "Letters stack into square blocks, one block per syllable: ㅎ+ㅏ+ㄴ = 한.": "made",
  "감사합니다": "made",
  "고양이": "made",
  "괜찮아요": "made",
  "글": "made",
  "김": "made",
  "김치": "made",
  "네": "made",
  "넷": "made",
  "다섯": "made",
  "둘": "made",
  "랑": "made",
  "맛있어요": "made",
  "몰라요": "made",
  "물": "made",
  "밥": "made",
  "사": "made",
  "사랑해요": "made",
  "선생님": "made",
  "셋": "made",
  "아니요": "made",
  "안녕하세요": "made",
  "안녕히 가세요": "made",
  "얼마예요": "made",
  "여기": "made",
  "이름": "made",
  "잘 자요": "made",
  "죄송합니다": "made",
  "집": "made",
  "치": "made",
  "친구": "made",
  "하나": "made",
  "학교": "made",
  "한": "made",
  "한국": "made",
  "행복해요": "made",
  "화장실": "made"
 },
 "mn": {
  "баярлалаа": "made",
  "баяртай": "made",
  "гуйя": "made",
  "гурав": "made",
  "найз": "made",
  "нэг": "made",
  "сайн байна уу": "made",
  "тийм": "made",
  "ус": "made",
  "уучлаарай": "made",
  "хайр": "made",
  "хоол": "made",
  "хоёр": "made",
  "хэд": "made",
  "үгүй": "made"
 },
 "mr": {
  "एक": "made",
  "किती": "made",
  "कृपया": "made",
  "जेवण": "made",
  "तीन": "made",
  "दोन": "made",
  "धन्यवाद": "made",
  "नमस्कार": "made",
  "नाही": "made",
  "पाणी": "made",
  "प्रेम": "made",
  "माफ करा": "made",
  "मित्र": "made",
  "येतो": "made",
  "होय": "made"
 },
 "ne": {
  "एक": "made",
  "कति": "made",
  "कृपया": "made",
  "खाना": "made",
  "तीन": "made",
  "दुई": "made",
  "धन्यवाद": "made",
  "नमस्ते": "made",
  "पानी": "made",
  "माफ गर्नुहोस्": "made",
  "माया": "made",
  "शौचालय": "made",
  "साथी": "made",
  "हो": "made",
  "होइन": "made"
 },
 "nl": {
  "alsjeblieft": "made",
  "dank je": "made",
  "doei": "made",
  "drie": "made",
  "een": "made",
  "eten": "made",
  "hallo": "made",
  "hoeveel": "made",
  "ja": "made",
  "liefde": "made",
  "nee": "made",
  "sorry": "made",
  "toilet": "made",
  "twee": "made",
  "vriend": "made",
  "water": "made"
 },
 "no": {
  "en": "made",
  "ha det": "made",
  "hei": "made",
  "hvor mye": "made",
  "ja": "made",
  "kjærlighet": "made",
  "mat": "made",
  "nei": "made",
  "takk": "made",
  "to": "made",
  "toalett": "made",
  "tre": "made",
  "unnskyld": "made",
  "vann": "made",
  "venn": "made",
  "vær så snill": "made"
 },
 "pl": {
  "cześć": "made",
  "do widzenia": "made",
  "dwa": "made",
  "dziękuję": "made",
  "ile": "made",
  "jeden": "made",
  "jedzenie": "made",
  "miłość": "made",
  "nie": "made",
  "proszę": "made",
  "przepraszam": "made",
  "przyjaciel": "made",
  "tak": "made",
  "toaleta": "made",
  "trzy": "made",
  "woda": "made"
 },
 "pt": {
  "amigo": "made",
  "amor": "made",
  "banheiro": "made",
  "comida": "made",
  "desculpe": "made",
  "dois": "made",
  "não": "made",
  "obrigado": "made",
  "olá": "made",
  "por favor": "made",
  "quanto": "made",
  "sim": "made",
  "tchau": "made",
  "três": "made",
  "um": "made",
  "água": "made"
 },
 "ro": {
  "apă": "made",
  "cât": "made",
  "da": "made",
  "doi": "made",
  "dragoste": "made",
  "la revedere": "made",
  "mulțumesc": "made",
  "mâncare": "made",
  "nu": "made",
  "prieten": "made",
  "salut": "made",
  "scuze": "made",
  "toaletă": "made",
  "trei": "made",
  "unu": "made",
  "vă rog": "made"
 },
 "ru": {
  "Watch the false friends: В=v, Н=n, Р=r, С=s, У=u, Х=kh.": "made",
  "Ё ё": "made",
  "А а": "made",
  "Б б": "made",
  "В в": "made",
  "Г г": "made",
  "Д д": "made",
  "Е е": "made",
  "Ж ж": "made",
  "З з": "made",
  "И и": "made",
  "Й й": "made",
  "К к": "made",
  "Л л": "made",
  "М м": "made",
  "Н н": "made",
  "О о": "made",
  "П п": "made",
  "Р р": "made",
  "Россия": "human",
  "С с": "made",
  "Т т": "made",
  "У у": "made",
  "Ф ф": "made",
  "Х х": "made",
  "Ц ц": "made",
  "Ч ч": "made",
  "Ш ш": "made",
  "Щ щ": "made",
  "Ъ ъ": "made",
  "Ы ы": "made",
  "Ь ь": "made",
  "Э э": "made",
  "Ю ю": "made",
  "Я я": "made",
  "вкусно": "made",
  "вода": "human",
  "вокзал": "made",
  "да": "human",
  "два": "human",
  "до свидания": "made",
  "доброе утро": "human",
  "дом": "made",
  "друг": "made",
  "здравствуйте": "human",
  "извините": "made",
  "имя": "made",
  "нет": "made",
  "один": "made",
  "пожалуйста": "made",
  "привет": "human",
  "пять": "made",
  "сколько стоит": "made",
  "собака": "made",
  "спасибо": "made",
  "три": "made",
  "туалет": "made",
  "учитель": "made",
  "хлеб": "made",
  "хорошо": "made",
  "чай": "made",
  "четыре": "made",
  "школа": "made",
  "я не понимаю": "made",
  "я тебя люблю": "made"
 },
 "sk": {
  "ahoj": "made",
  "dovidenia": "made",
  "dva": "made",
  "jeden": "made",
  "jedlo": "made",
  "koľko": "made",
  "láska": "made",
  "nie": "made",
  "prepáčte": "made",
  "priateľ": "made",
  "prosím": "made",
  "tri": "made",
  "voda": "made",
  "záchod": "made",
  "áno": "made",
  "ďakujem": "made"
 },
 "so": {
  "biyo": "made",
  "cunto": "made",
  "fadlan": "made",
  "haa": "made",
  "immisa": "made",
  "jacayl": "made",
  "kow": "made",
  "laba": "made",
  "mahadsanid": "made",
  "maya": "made",
  "musqul": "made",
  "nabadgelyo": "made",
  "raali ahow": "made",
  "saaxiib": "made",
  "saddex": "made",
  "salaan": "made"
 },
 "sq": {
  "banjo": "made",
  "dashuri": "made",
  "dy": "made",
  "faleminderit": "made",
  "jo": "made",
  "ju lutem": "made",
  "mik": "made",
  "mirupafshim": "made",
  "më fal": "made",
  "një": "made",
  "po": "made",
  "përshëndetje": "made",
  "sa": "made",
  "tre": "made",
  "ujë": "made",
  "ushqim": "made"
 },
 "sr": {
  "вода": "made",
  "да": "made",
  "два": "made",
  "довиђења": "made",
  "здраво": "made",
  "извините": "made",
  "колико": "made",
  "молим": "made",
  "не": "made",
  "пријатељ": "made",
  "тоалет": "made",
  "три": "made",
  "хвала": "made",
  "храна": "made",
  "један": "made",
  "љубав": "made"
 },
 "sv": {
  "ett": "made",
  "förlåt": "made",
  "hej": "made",
  "hej då": "made",
  "hur mycket": "made",
  "ja": "made",
  "kärlek": "made",
  "mat": "made",
  "nej": "made",
  "snälla": "made",
  "tack": "made",
  "toalett": "made",
  "tre": "made",
  "två": "made",
  "vatten": "made",
  "vän": "made"
 },
 "sw": {
  "asante": "human",
  "bei gani": "made",
  "chakula": "human",
  "choo": "made",
  "hapana": "made",
  "jambo": "made",
  "kwaheri": "made",
  "maji": "made",
  "mbili": "made",
  "moja": "made",
  "ndiyo": "made",
  "rafiki": "made",
  "samahani": "made",
  "tafadhali": "made",
  "tatu": "made",
  "upendo": "made"
 },
 "ta": {
  "அன்பு": "made",
  "ஆம்": "made",
  "இரண்டு": "made",
  "இல்லை": "made",
  "உணவு": "made",
  "எவ்வளவு": "made",
  "ஒன்று": "made",
  "தண்ணீர்": "made",
  "தயவுசெய்து": "made",
  "நண்பன்": "made",
  "நன்றி": "made",
  "மன்னிக்கவும்": "made",
  "மூன்று": "made",
  "வணக்கம்": "made"
 },
 "th": {
  "กรุณา": "made",
  "ขอบคุณ": "made",
  "ขอโทษ": "made",
  "ความรัก": "made",
  "น้ำ": "made",
  "ลาก่อน": "made",
  "สวัสดี": "made",
  "สอง": "made",
  "สาม": "made",
  "หนึ่ง": "made",
  "ห้องน้ำ": "made",
  "อาหาร": "made",
  "เท่าไร": "made",
  "เพื่อน": "made",
  "ใช่": "made",
  "ไม่": "made"
 },
 "tl": {
  "banyo": "made",
  "dalawa": "made",
  "hindi": "made",
  "isa": "made",
  "kaibigan": "made",
  "kumusta": "made",
  "magkano": "made",
  "oo": "made",
  "paalam": "made",
  "pag-ibig": "made",
  "pagkain": "made",
  "pakiusap": "made",
  "pasensya": "made",
  "salamat": "made",
  "tatlo": "made",
  "tubig": "made"
 },
 "tr": {
  "affedersiniz": "made",
  "arkadaş": "made",
  "aşk": "made",
  "bir": "made",
  "evet": "made",
  "hayır": "made",
  "hoşça kal": "made",
  "iki": "made",
  "lütfen": "made",
  "merhaba": "made",
  "ne kadar": "made",
  "su": "made",
  "teşekkürler": "made",
  "tuvalet": "made",
  "yemek": "made",
  "üç": "made"
 },
 "uk": {
  "будь ласка": "made",
  "вибачте": "made",
  "вода": "made",
  "два": "made",
  "до побачення": "made",
  "друг": "made",
  "дякую": "made",
  "любов": "made",
  "ні": "made",
  "один": "made",
  "привіт": "made",
  "скільки": "made",
  "так": "made",
  "три": "made",
  "туалет": "made",
  "їжа": "made"
 },
 "ur": {
  "السلام علیکم": "made",
  "ایک": "made",
  "باتھ روم": "made",
  "تین": "made",
  "خدا حافظ": "made",
  "دو": "made",
  "دوست": "made",
  "شکریہ": "made",
  "محبت": "made",
  "معاف کیجیے": "made",
  "مہربانی": "made",
  "نہیں": "made",
  "پانی": "made",
  "کتنا": "made",
  "کھانا": "made",
  "ہاں": "made"
 },
 "vi": {
  "ba": "made",
  "bao nhiêu": "made",
  "bạn": "made",
  "cảm ơn": "made",
  "hai": "made",
  "không": "made",
  "làm ơn": "made",
  "một": "made",
  "nhà vệ sinh": "made",
  "nước": "made",
  "thức ăn": "made",
  "tình yêu": "made",
  "tạm biệt": "made",
  "vâng": "made",
  "xin chào": "made",
  "xin lỗi": "made"
 },
 "yo": {
  "báwo ni": "made",
  "bẹ́ẹ̀ ni": "made",
  "e ṣé": "made",
  "jọ̀wọ́": "made",
  "mà bínú": "made",
  "mélòó": "made",
  "omi": "made",
  "oúnjẹ": "made",
  "rárá": "made",
  "èjì": "made",
  "ìfẹ́": "made",
  "ó dàbọ̀": "made",
  "ẹ̀ta": "made",
  "ọ̀kan": "made",
  "ọ̀rẹ́": "made"
 },
 "zh": {
  "-i (after zh ch sh r z c s)": "made",
  "Stroke order: top to bottom, left to right, horizontal before vertical.": "made",
  "The tone mark sits on the vowel: mā má mǎ mà are four different words.": "made",
  "b": "made",
  "c": "made",
  "ch": "made",
  "e": "made",
  "hiragana": "made",
  "ian": "made",
  "iu": "made",
  "j": "made",
  "ma 吗": "made",
  "mà 骂": "made",
  "má 麻": "made",
  "mā 妈": "made",
  "mǎ 马": "made",
  "ong": "made",
  "p": "made",
  "q": "made",
  "r": "made",
  "sh": "made",
  "ui": "made",
  "x": "made",
  "z": "made",
  "zh": "made",
  "ü": "made",
  "一": "made",
  "七": "made",
  "三": "made",
  "不客气": "made",
  "不是": "made",
  "中": "made",
  "中国": "made",
  "九": "made",
  "二": "made",
  "五": "made",
  "人": "made",
  "你好": "made",
  "八": "made",
  "六": "made",
  "再见": "made",
  "十": "made",
  "名字": "made",
  "四": "made",
  "国": "made",
  "多少钱": "made",
  "大": "made",
  "好": "made",
  "好吃": "made",
  "学校": "made",
  "对不起": "made",
  "小": "made",
  "山": "made",
  "很高兴": "made",
  "我": "made",
  "我不懂": "made",
  "我爱你": "made",
  "日": "made",
  "早上好": "made",
  "是": "made",
  "月": "made",
  "朋友": "made",
  "水": "made",
  "洗手间": "made",
  "火": "made",
  "火车站": "made",
  "狗": "made",
  "猫": "made",
  "米饭": "made",
  "老师": "made",
  "茶": "made",
  "谢谢": "made"
 },
 "zu": {
  "amanzi": "made",
  "kubili": "made",
  "kunye": "made",
  "kuthathu": "made",
  "malini": "made",
  "ngicela": "made",
  "ngiyabonga": "made",
  "sala kahle": "made",
  "sawubona": "made",
  "ukudla": "made",
  "umngane": "made",
  "uthando": "made",
  "uxolo": "made",
  "yebo": "made"
 }
};
