/* written by tools/get-recordings.py - do not edit */
window.RECORDINGS = {
 "af": {
  "asseblief": "asseblief.wav",
  "dankie": "dankie.wav",
  "drie": "drie.wav",
  "een": "een.wav",
  "hallo": "hallo.wav",
  "hoeveel": "hoeveel.wav",
  "ja": "ja.wav",
  "jammer": "jammer.wav",
  "kos": "kos.wav",
  "liefde": "liefde.wav",
  "nee": "nee.wav",
  "toilet": "toilet.wav",
  "totsiens": "totsiens.wav",
  "twee": "twee.wav",
  "vriend": "vriend.wav",
  "water": "water.wav"
 },
 "am": {
  "ሁለት": "ሁለት.wav",
  "ምግብ": "ምግብ.wav",
  "ሰላም": "ሰላም.wav",
  "ስንት": "ስንት.wav",
  "ሶስት": "ሶስት.wav",
  "አመሰግናለሁ": "አመሰግናለሁ.wav",
  "አንድ": "አንድ.wav",
  "አዎ": "አዎ.wav",
  "አይደለም": "አይደለም.wav",
  "እባክህ": "እባክህ.wav",
  "ውሃ": "ውሃ.wav",
  "ይቅርታ": "ይቅርታ.wav",
  "ደህና ሁን": "ደህና_ሁን.wav",
  "ጓደኛ": "ጓደኛ.wav",
  "ፍቅር": "ፍቅር.wav"
 },
 "ar": {
  "آسف": "آسف.wav",
  "أحبك": "أحبك.wav",
  "أربعة": "أربعة.wav",
  "اثنان": "اثنان.wav",
  "اسم": "اسم.wav",
  "السلام عليكم": "السلام_عليكم.wav",
  "بيت": "بيت.wav",
  "ثلاثة": "ثلاثة.wav",
  "جميل": "جميل.wav",
  "حمام": "حمام.wav",
  "خبز": "خبز.wav",
  "خمسة": "خمسة.wav",
  "شاي": "شاي.wav",
  "شكرا": "شكرا.wav",
  "صباح الخير": "صباح_الخير.wav",
  "صديق": "صديق.wav",
  "قطة": "قطة.wav",
  "كم الثمن": "كم_الثمن.wav",
  "لا": "لا.wav",
  "لا أفهم": "لا_أفهم.wav",
  "لذيذ": "لذيذ.wav",
  "مدرسة": "مدرسة.wav",
  "مرحبا": "مرحبا.wav",
  "مصر": "مصر.wav",
  "مع السلامة": "مع_السلامة.wav",
  "معلم": "معلم.wav",
  "من فضلك": "من_فضلك.wav",
  "نعم": "نعم.wav",
  "واحد": "واحد.wav"
 },
 "bg": {
  "благодаря": "благодаря.wav",
  "вода": "вода.wav",
  "да": "да.wav",
  "две": "две.wav",
  "довиждане": "довиждане.wav",
  "едно": "едно.wav",
  "здравей": "здравей.wav",
  "извинете": "извинете.wav",
  "колко": "колко.wav",
  "любов": "любов.wav",
  "моля": "моля.wav",
  "не": "не.wav",
  "приятел": "приятел.wav",
  "тоалетна": "тоалетна.wav",
  "три": "три.wav",
  "храна": "храна.wav"
 },
 "bn": {
  "এক": "এক.wav",
  "কত": "কত.wav",
  "খাবার": "খ_ব_র.wav",
  "জল": "জল.wav",
  "তিন": "ত_ন.wav",
  "দয়া করে": "দয_কর.wav",
  "দুঃখিত": "দ_খ_ত.wav",
  "দুই": "দ_ই.wav",
  "ধন্যবাদ": "ধন_যব_দ.wav",
  "নমস্কার": "নমস_ক_র.wav",
  "না": "ন.wav",
  "বন্ধু": "বন_ধ.wav",
  "বাথরুম": "ব_থর_ম.wav",
  "বিদায়": "ব_দ_য.wav",
  "ভালোবাসা": "ভ_ল_ব_স.wav",
  "হ্যাঁ": "হ_য.wav"
 },
 "ca": {
  "adéu": "adéu.wav",
  "aigua": "aigua.wav",
  "amic": "amic.wav",
  "amor": "amor.wav",
  "dos": "dos.wav",
  "gràcies": "gràcies.wav",
  "hola": "hola.wav",
  "lavabo": "lavabo.wav",
  "menjar": "menjar.wav",
  "no": "no.wav",
  "perdó": "perdó.wav",
  "quant": "quant.wav",
  "si us plau": "si_us_plau.wav",
  "sí": "sí.wav",
  "tres": "tres.wav",
  "un": "un.wav"
 },
 "cs": {
  "ahoj": "ahoj.wav",
  "ano": "ano.wav",
  "dva": "dva.wav",
  "děkuji": "děkuji.wav",
  "jeden": "jeden.wav",
  "jídlo": "jídlo.wav",
  "kolik": "kolik.wav",
  "láska": "láska.wav",
  "na shledanou": "na_shledanou.wav",
  "ne": "ne.wav",
  "promiňte": "promiňte.wav",
  "prosím": "prosím.wav",
  "přítel": "přítel.wav",
  "tři": "tři.wav",
  "voda": "voda.wav",
  "záchod": "záchod.wav"
 },
 "da": {
  "en": "en.wav",
  "farvel": "farvel.wav",
  "hej": "hej.wav",
  "hvor meget": "hvor_meget.wav",
  "ja": "ja.wav",
  "kærlighed": "kærlighed.wav",
  "mad": "mad.wav",
  "nej": "nej.wav",
  "tak": "tak.wav",
  "to": "to.wav",
  "toilet": "toilet.wav",
  "tre": "tre.wav",
  "undskyld": "undskyld.wav",
  "vand": "vand.wav",
  "ven": "ven.wav",
  "vær så god": "vær_så_god.wav"
 },
 "de": {
  "Essen": "Essen.ogg",
  "Freund": "Freund.ogg",
  "Liebe": "Liebe.ogg",
  "Toilette": "Toilette.ogg",
  "Wasser": "Wasser.ogg",
  "bitte": "bitte.ogg",
  "danke": "danke.ogg",
  "drei": "drei.wav",
  "eins": "eins.ogg",
  "entschuldigung": "entschuldigung.wav",
  "hallo": "hallo.ogg",
  "ja": "ja.ogg",
  "nein": "nein.wav",
  "tschüss": "tschüss.ogg",
  "wie viel": "wie_viel.oga",
  "zwei": "zwei.ogg"
 },
 "el": {
  "Ελλάδα": "Ελλάδα.wav",
  "ένα": "ένα.wav",
  "αντίο": "αντίο.wav",
  "γάτα": "γάτα.wav",
  "γεια σου": "γεια_σου.wav",
  "δάσκαλος": "δάσκαλος.wav",
  "δεν καταλαβαίνω": "δεν_καταλαβαίνω.wav",
  "δύο": "δύο.wav",
  "ευχαριστώ": "ευχαριστώ.wav",
  "καλημέρα": "καλημέρα.wav",
  "καλησπέρα": "καλησπέρα.wav",
  "καφές": "καφές.wav",
  "ναι": "ναι.wav",
  "νερό": "νερό.wav",
  "νόστιμο": "νόστιμο.wav",
  "πέντε": "πέντε.wav",
  "παρακαλώ": "παρακαλώ.wav",
  "πόσο κάνει": "πόσο_κάνει.wav",
  "σκύλος": "σκύλος.wav",
  "σπίτι": "σπίτι.wav",
  "συγγνώμη": "συγγνώμη.wav",
  "σχολείο": "σχολείο.wav",
  "τέσσερα": "τέσσερα.wav",
  "τουαλέτα": "τουαλέτα.wav",
  "τρία": "τρία.wav",
  "φίλος": "φίλος.wav",
  "ψωμί": "ψωμί.wav",
  "ωραία": "ωραία.wav",
  "όνομα": "όνομα.wav",
  "όχι": "όχι.wav"
 },
 "en": {
  "food": "food.wav",
  "friend": "friend.wav",
  "goodbye": "goodbye.wav",
  "hello": "hello.wav",
  "how much": "how_much.wav",
  "love": "love.wav",
  "no": "no.wav",
  "one": "one.wav",
  "please": "please.wav",
  "sorry": "sorry.wav",
  "thank you": "thank_you.wav",
  "three": "three.wav",
  "toilet": "toilet.wav",
  "two": "two.wav",
  "water": "water.wav",
  "yes": "yes.wav"
 },
 "eo": {
  "akvo": "akvo.wav",
  "amiko": "amiko.wav",
  "amo": "amo.wav",
  "bonvolu": "bonvolu.wav",
  "dankon": "dankon.wav",
  "du": "du.wav",
  "jes": "jes.wav",
  "kiom": "kiom.wav",
  "manĝaĵo": "manĝaĵo.wav",
  "ne": "ne.wav",
  "necesejo": "necesejo.wav",
  "pardonu": "pardonu.wav",
  "saluton": "saluton.wav",
  "tri": "tri.wav",
  "unu": "unu.wav",
  "ĝis revido": "ĝis_revido.wav"
 },
 "es": {
  "España": "España.wav",
  "adiós": "adiós.wav",
  "agua": "agua.wav",
  "amigo": "amigo.wav",
  "baño": "baño.wav",
  "buenos días": "buenos_días.wav",
  "café": "café.wav",
  "casa": "casa.wav",
  "cinco": "cinco.wav",
  "cuatro": "cuatro.wav",
  "cuánto cuesta": "cuánto_cuesta.wav",
  "delicioso": "delicioso.wav",
  "dos": "dos.wav",
  "escuela": "escuela.wav",
  "feliz": "feliz.wav",
  "gracias": "gracias.wav",
  "hola": "hola.wav",
  "lo siento": "lo_siento.wav",
  "maestro": "maestro.wav",
  "no": "no.wav",
  "no entiendo": "no_entiendo.wav",
  "nombre": "nombre.wav",
  "pan": "pan.wav",
  "perro": "perro.wav",
  "por favor": "por_favor.wav",
  "sí": "sí.wav",
  "te quiero": "te_quiero.wav",
  "tres": "tres.wav",
  "uno": "uno.wav"
 },
 "fa": {
  "آب": "آب.wav",
  "ببخشید": "ببخشید.wav",
  "بله": "بله.wav",
  "خداحافظ": "خداحافظ.wav",
  "دستشویی": "دستشویی.wav",
  "دو": "دو.wav",
  "دوست": "دوست.wav",
  "سلام": "سلام.wav",
  "سه": "سه.wav",
  "عشق": "عشق.wav",
  "غذا": "غذا.wav",
  "لطفا": "لطفا.wav",
  "ممنون": "ممنون.wav",
  "نه": "نه.wav",
  "چند": "چند.wav",
  "یک": "یک.wav"
 },
 "fi": {
  "anteeksi": "anteeksi.wav",
  "ei": "ei.wav",
  "hei": "hei.wav",
  "kaksi": "kaksi.wav",
  "kiitos": "kiitos.wav",
  "kolme": "kolme.wav",
  "kyllä": "kyllä.wav",
  "näkemiin": "näkemiin.wav",
  "ole hyvä": "ole_hyvä.wav",
  "paljonko": "paljonko.wav",
  "rakkaus": "rakkaus.wav",
  "ruoka": "ruoka.wav",
  "vesi": "vesi.wav",
  "vessa": "vessa.wav",
  "yksi": "yksi.wav",
  "ystävä": "ystävä.wav"
 },
 "fr": {
  "France": "France.wav",
  "ami": "ami.wav",
  "au revoir": "au_revoir.wav",
  "bonjour": "bonjour.wav",
  "bonsoir": "bonsoir.wav",
  "café": "café.wav",
  "chat": "chat.wav",
  "chien": "chien.wav",
  "cinq": "cinq.wav",
  "combien": "combien.wav",
  "deux": "deux.wav",
  "délicieux": "délicieux.wav",
  "eau": "eau.wav",
  "heureux": "heureux.wav",
  "ja": "ja.wav",
  "je ne comprends pas": "je_ne_comprends_pas.wav",
  "maison": "maison.wav",
  "merci": "merci.wav",
  "nom": "nom.wav",
  "non": "non.wav",
  "oui": "oui.wav",
  "pain": "pain.wav",
  "pardon": "pardon.wav",
  "professeur": "professeur.wav",
  "quatre": "quatre.wav",
  "toilettes": "toilettes.wav",
  "trois": "trois.wav",
  "un": "un.wav",
  "école": "école.wav"
 },
 "he": {
  "אהבה": "אהבה.wav",
  "אוכל": "אוכל.wav",
  "אחד": "אחד.wav",
  "בבקשה": "בבקשה.wav",
  "חבר": "חבר.wav",
  "כמה": "כמה.wav",
  "כן": "כן.wav",
  "לא": "לא.wav",
  "להתראות": "להתראות.wav",
  "מים": "מים.wav",
  "סליחה": "סליחה.wav",
  "שירותים": "שירותים.wav",
  "שלום": "שלום.wav",
  "שלוש": "שלוש.wav",
  "שתיים": "שתיים.wav",
  "תודה": "תודה.wav"
 },
 "hi": {
  "अच्छा": "अच_छ.wav",
  "एक": "एक.wav",
  "कितने का है": "क_तन_क_ह.wav",
  "कुत्ता": "क_त_त.wav",
  "कृपया": "क_पय.wav",
  "घर": "घर.wav",
  "चाय": "च_य.wav",
  "चार": "च_र.wav",
  "चावल": "च_वल.wav",
  "तीन": "त_न.wav",
  "दो": "द.wav",
  "दोस्त": "द_स_त.wav",
  "धन्यवाद": "धन_यव_द.wav",
  "नमस्ते": "नमस_त.wav",
  "नहीं": "नह.wav",
  "नाम": "न_म.wav",
  "पाँच": "प_च.wav",
  "पानी": "प_न.wav",
  "प्यार": "प_य_र.wav",
  "फिर मिलेंगे": "फ_र_म_ल_ग.wav",
  "बिल्ली": "ब_ल_ल.wav",
  "भारत": "भ_रत.wav",
  "माफ़ कीजिए": "म_फ_क_ज_ए.wav",
  "शिक्षक": "श_क_षक.wav",
  "शौचालय": "श_च_लय.wav",
  "समझ नहीं आया": "समझ_नह_आय.wav",
  "सुप्रभात": "स_प_रभ_त.wav",
  "स्कूल": "स_क_ल.wav",
  "स्वादिष्ट": "स_व_द_ष_ट.wav",
  "हाँ": "ह.wav"
 },
 "hr": {
  "bok": "bok.wav",
  "da": "da.wav",
  "doviđenja": "doviđenja.wav",
  "dva": "dva.wav",
  "hrana": "hrana.wav",
  "hvala": "hvala.wav",
  "jedan": "jedan.wav",
  "koliko": "koliko.wav",
  "ljubav": "ljubav.wav",
  "molim": "molim.wav",
  "ne": "ne.wav",
  "oprostite": "oprostite.wav",
  "prijatelj": "prijatelj.wav",
  "tri": "tri.wav",
  "voda": "voda.wav",
  "zahod": "zahod.wav"
 },
 "ht": {
  "bonjou": "bonjou.wav",
  "de": "de.wav",
  "dlo": "dlo.wav",
  "eskize m": "eskize_m.wav",
  "konbyen": "konbyen.wav",
  "lanmou": "lanmou.wav",
  "manje": "manje.wav",
  "mèsi": "mèsi.wav",
  "non": "non.wav",
  "orevwa": "orevwa.wav",
  "souple": "souple.wav",
  "twa": "twa.wav",
  "twalèt": "twalèt.wav",
  "wi": "wi.wav",
  "youn": "youn.wav",
  "zanmi": "zanmi.wav"
 },
 "hu": {
  "barát": "barát.wav",
  "bocsánat": "bocsánat.wav",
  "egy": "egy.wav",
  "három": "három.wav",
  "igen": "igen.wav",
  "kettő": "kettő.wav",
  "kérem": "kérem.wav",
  "köszönöm": "köszönöm.wav",
  "mennyibe": "mennyibe.wav",
  "mosdó": "mosdó.wav",
  "nem": "nem.wav",
  "szerelem": "szerelem.wav",
  "szia": "szia.wav",
  "viszlát": "viszlát.wav",
  "víz": "víz.wav",
  "étel": "étel.wav"
 },
 "hy": {
  "այո": "այո.wav",
  "բարև": "բարև.wav",
  "երեք": "երեք.wav",
  "երկու": "երկու.wav",
  "զուգարան": "զուգարան.wav",
  "ընկեր": "ընկեր.wav",
  "ինչքան": "ինչքան.wav",
  "խնդրեմ": "խնդրեմ.wav",
  "մեկ": "մեկ.wav",
  "ներողություն": "ներողություն.wav",
  "շնորհակալություն": "շնորհակալություն.wav",
  "ոչ": "ոչ.wav",
  "ուտելիք": "ուտելիք.wav",
  "ջուր": "ջուր.wav",
  "սեր": "սեր.wav",
  "ցտեսություն": "ցտեսություն.wav"
 },
 "id": {
  "air": "air.wav",
  "berapa": "berapa.wav",
  "cinta": "cinta.wav",
  "dua": "dua.wav",
  "halo": "halo.wav",
  "maaf": "maaf.wav",
  "makanan": "makanan.wav",
  "satu": "satu.wav",
  "selamat tinggal": "selamat_tinggal.wav",
  "teman": "teman.wav",
  "terima kasih": "terima_kasih.wav",
  "tidak": "tidak.wav",
  "tiga": "tiga.wav",
  "toilet": "toilet.wav",
  "tolong": "tolong.wav",
  "ya": "ya.wav"
 },
 "it": {
  "acqua": "acqua.wav",
  "amico": "amico.wav",
  "amore": "amore.wav",
  "arrivederci": "arrivederci.wav",
  "bagno": "bagno.wav",
  "ciao": "ciao.wav",
  "cibo": "cibo.wav",
  "due": "due.wav",
  "grazie": "grazie.wav",
  "no": "no.wav",
  "per favore": "per_favore.wav",
  "quanto": "quanto.wav",
  "scusa": "scusa.wav",
  "sì": "sì.wav",
  "tre": "tre.wav",
  "uno": "uno.wav"
 },
 "ja": {
  "ありがとう": "ありがとう.wav",
  "いいえ": "いいえ.wav",
  "いくらですか": "いくらですか.wav",
  "いただきます": "いただきます.wav",
  "おはようございます": "おはようございます.wav",
  "お茶": "お茶.wav",
  "お願いします": "お願いします.wav",
  "こんにちは": "こんにちは.wav",
  "こんばんは": "こんばんは.wav",
  "ご飯": "ご飯.wav",
  "さようなら": "さようなら.wav",
  "すみません": "すみません.wav",
  "はい": "はい.wav",
  "またね": "またね.wav",
  "トイレはどこですか": "トイレはどこですか.wav",
  "一": "一.wav",
  "三": "三.wav",
  "二": "二.wav",
  "五": "五.wav",
  "元気ですか": "元気ですか.wav",
  "先生": "先生.wav",
  "分かりません": "分かりません.wav",
  "友達": "友達.wav",
  "名前": "名前.wav",
  "四": "四.wav",
  "大丈夫": "大丈夫.wav",
  "学校": "学校.wav",
  "愛": "愛.wav",
  "日本": "日本.wav",
  "楽しい": "楽しい.wav",
  "水": "水.wav",
  "犬": "犬.wav",
  "猫": "猫.wav",
  "美味しい": "美味しい.wav",
  "駅": "駅.wav"
 },
 "ka": {
  "არა": "არა.wav",
  "ბოდიши": "ბოდიши.wav",
  "გამარჯობა": "გამარჯობა.wav",
  "გთხოვთ": "გთხოვთ.wav",
  "ერთი": "ერთი.wav",
  "კი": "კი.wav",
  "მადლობა": "მადლობა.wav",
  "მეგობარი": "მეგობარი.wav",
  "ნახვამდის": "ნახვამდის.wav",
  "ორი": "ორი.wav",
  "რამდენი": "რამდენი.wav",
  "სამი": "სამი.wav",
  "საჭმელი": "საჭმელი.wav",
  "სიყვარული": "სიყვარული.wav",
  "ტუალეტი": "ტუალეტი.wav",
  "წყალი": "წყალი.wav"
 },
 "ko": {
  "감사합니다": "감사합니다.wav",
  "고양이": "고양이.wav",
  "괜찮아요": "괜찮아요.wav",
  "김치": "김치.wav",
  "네": "네.wav",
  "넷": "넷.wav",
  "다섯": "다섯.wav",
  "둘": "둘.wav",
  "맛있어요": "맛있어요.wav",
  "몰라요": "몰라요.wav",
  "물": "물.wav",
  "밥": "밥.wav",
  "사랑해요": "사랑해요.wav",
  "선생님": "선생님.wav",
  "셋": "셋.wav",
  "아니요": "아니요.wav",
  "안녕하세요": "안녕하세요.wav",
  "안녕히 가세요": "안녕히_가세요.wav",
  "얼마예요": "얼마예요.wav",
  "여기": "여기.wav",
  "이름": "이름.wav",
  "잘 자요": "잘_자요.wav",
  "죄송합니다": "죄송합니다.wav",
  "집": "집.wav",
  "친구": "친구.wav",
  "하나": "하나.wav",
  "학교": "학교.wav",
  "한국": "한국.wav",
  "행복해요": "행복해요.wav",
  "화장실": "화장실.wav"
 },
 "mn": {
  "баярлалаа": "баярлалаа.mp3",
  "баяртай": "баяртай.mp3",
  "гуйя": "гуйя.mp3",
  "гурав": "гурав.mp3",
  "найз": "найз.mp3",
  "нэг": "нэг.mp3",
  "сайн байна уу": "сайн_байна_уу.mp3",
  "тийм": "тийм.mp3",
  "ус": "ус.mp3",
  "уучлаарай": "уучлаарай.mp3",
  "хайр": "хайр.mp3",
  "хоол": "хоол.mp3",
  "хоёр": "хоёр.mp3",
  "хэд": "хэд.mp3",
  "үгүй": "үгүй.mp3"
 },
 "mr": {
  "एक": "एक.wav",
  "किती": "क_त.wav",
  "कृपया": "क_पय.wav",
  "जेवण": "ज_वण.wav",
  "तीन": "त_न.wav",
  "दोन": "द_न.wav",
  "धन्यवाद": "धन_यव_द.wav",
  "नमस्कार": "नमस_क_र.wav",
  "नाही": "न_ह.wav",
  "पाणी": "प_ण.wav",
  "प्रेम": "प_र_म.wav",
  "माफ करा": "म_फ_कर.wav",
  "मित्र": "म_त_र.wav",
  "येतो": "य_त.wav",
  "होय": "ह_य.wav"
 },
 "ne": {
  "एक": "एक.wav",
  "कति": "कत.wav",
  "कृपया": "क_पय.wav",
  "खाना": "ख_न.wav",
  "तीन": "त_न.wav",
  "दुई": "द_ई.wav",
  "धन्यवाद": "धन_यव_द.wav",
  "नमस्ते": "नमस_त.wav",
  "पानी": "प_न.wav",
  "माफ गर्नुहोस्": "म_फ_गर_न_ह_स.wav",
  "माया": "म_य.wav",
  "शौचालय": "श_च_लय.wav",
  "साथी": "स_थ.wav",
  "हो": "ह.wav",
  "होइन": "ह_इन.wav"
 },
 "nl": {
  "alsjeblieft": "alsjeblieft.wav",
  "dank je": "dank_je.wav",
  "doei": "doei.wav",
  "drie": "drie.wav",
  "een": "een.wav",
  "eten": "eten.wav",
  "hallo": "hallo.wav",
  "hoeveel": "hoeveel.wav",
  "ja": "ja.wav",
  "liefde": "liefde.wav",
  "nee": "nee.wav",
  "sorry": "sorry.wav",
  "toilet": "toilet.wav",
  "twee": "twee.wav",
  "vriend": "vriend.wav",
  "water": "water.wav"
 },
 "no": {
  "en": "en.wav",
  "ha det": "ha_det.wav",
  "hei": "hei.wav",
  "hvor mye": "hvor_mye.wav",
  "ja": "ja.wav",
  "kjærlighet": "kjærlighet.wav",
  "mat": "mat.wav",
  "nei": "nei.wav",
  "takk": "takk.wav",
  "to": "to.wav",
  "toalett": "toalett.wav",
  "tre": "tre.wav",
  "unnskyld": "unnskyld.wav",
  "vann": "vann.wav",
  "venn": "venn.wav",
  "vær så snill": "vær_så_snill.wav"
 },
 "pl": {
  "cześć": "cześć.wav",
  "do widzenia": "do_widzenia.wav",
  "dwa": "dwa.wav",
  "dziękuję": "dziękuję.wav",
  "ile": "ile.wav",
  "jeden": "jeden.wav",
  "jedzenie": "jedzenie.wav",
  "miłość": "miłość.wav",
  "nie": "nie.wav",
  "proszę": "proszę.wav",
  "przepraszam": "przepraszam.wav",
  "przyjaciel": "przyjaciel.wav",
  "tak": "tak.wav",
  "toaleta": "toaleta.wav",
  "trzy": "trzy.wav",
  "woda": "woda.wav"
 },
 "pt": {
  "amigo": "amigo.wav",
  "amor": "amor.wav",
  "banheiro": "banheiro.wav",
  "comida": "comida.wav",
  "desculpe": "desculpe.wav",
  "dois": "dois.wav",
  "não": "não.wav",
  "obrigado": "obrigado.wav",
  "olá": "olá.wav",
  "por favor": "por_favor.wav",
  "quanto": "quanto.wav",
  "sim": "sim.wav",
  "tchau": "tchau.wav",
  "três": "três.wav",
  "um": "um.wav",
  "água": "água.wav"
 },
 "ro": {
  "apă": "apă.wav",
  "cât": "cât.wav",
  "da": "da.wav",
  "doi": "doi.wav",
  "dragoste": "dragoste.wav",
  "la revedere": "la_revedere.wav",
  "mulțumesc": "mulțumesc.wav",
  "mâncare": "mâncare.wav",
  "nu": "nu.wav",
  "prieten": "prieten.wav",
  "salut": "salut.wav",
  "scuze": "scuze.wav",
  "toaletă": "toaletă.wav",
  "trei": "trei.wav",
  "unu": "unu.wav",
  "vă rog": "vă_rog.wav"
 },
 "ru": {
  "Россия": "Россия.ogg",
  "вкусно": "вкусно.wav",
  "вода": "вода.ogg",
  "вокзал": "вокзал.wav",
  "да": "да.ogg",
  "два": "два.ogg",
  "до свидания": "до_свидания.wav",
  "доброе утро": "доброе_утро.wav",
  "дом": "дом.wav",
  "друг": "друг.wav",
  "здравствуйте": "здравствуйте.wav",
  "извините": "извините.wav",
  "имя": "имя.wav",
  "нет": "нет.wav",
  "один": "один.wav",
  "пожалуйста": "пожалуйста.wav",
  "привет": "привет.wav",
  "пять": "пять.wav",
  "сколько стоит": "сколько_стоит.wav",
  "собака": "собака.wav",
  "спасибо": "спасибо.wav",
  "три": "три.wav",
  "туалет": "туалет.wav",
  "учитель": "учитель.wav",
  "хлеб": "хлеб.wav",
  "хорошо": "хорошо.wav",
  "чай": "чай.wav",
  "четыре": "четыре.wav",
  "школа": "школа.wav",
  "я не понимаю": "я_не_понимаю.wav",
  "я тебя люблю": "я_тебя_люблю.wav"
 },
 "sk": {
  "ahoj": "ahoj.wav",
  "dovidenia": "dovidenia.wav",
  "dva": "dva.wav",
  "jeden": "jeden.wav",
  "jedlo": "jedlo.wav",
  "koľko": "koľko.wav",
  "láska": "láska.wav",
  "nie": "nie.wav",
  "prepáčte": "prepáčte.wav",
  "priateľ": "priateľ.wav",
  "prosím": "prosím.wav",
  "tri": "tri.wav",
  "voda": "voda.wav",
  "záchod": "záchod.wav",
  "áno": "áno.wav",
  "ďakujem": "ďakujem.wav"
 },
 "so": {
  "biyo": "biyo.mp3",
  "cunto": "cunto.mp3",
  "fadlan": "fadlan.mp3",
  "haa": "haa.mp3",
  "immisa": "immisa.mp3",
  "jacayl": "jacayl.mp3",
  "kow": "kow.mp3",
  "laba": "laba.mp3",
  "mahadsanid": "mahadsanid.mp3",
  "maya": "maya.mp3",
  "musqul": "musqul.mp3",
  "nabadgelyo": "nabadgelyo.mp3",
  "raali ahow": "raali_ahow.mp3",
  "saaxiib": "saaxiib.mp3",
  "saddex": "saddex.mp3",
  "salaan": "salaan.mp3"
 },
 "sq": {
  "banjo": "banjo.wav",
  "dashuri": "dashuri.wav",
  "dy": "dy.wav",
  "faleminderit": "faleminderit.wav",
  "jo": "jo.wav",
  "ju lutem": "ju_lutem.wav",
  "mik": "mik.wav",
  "mirupafshim": "mirupafshim.wav",
  "më fal": "më_fal.wav",
  "një": "një.wav",
  "po": "po.wav",
  "përshëndetje": "përshëndetje.wav",
  "sa": "sa.wav",
  "tre": "tre.wav",
  "ujë": "ujë.wav",
  "ushqim": "ushqim.wav"
 },
 "sr": {
  "вода": "вода.wav",
  "да": "да.wav",
  "два": "два.wav",
  "довиђења": "довиђења.wav",
  "здраво": "здраво.wav",
  "извините": "извините.wav",
  "колико": "колико.wav",
  "молим": "молим.wav",
  "не": "не.wav",
  "пријатељ": "пријатељ.wav",
  "тоалет": "тоалет.wav",
  "три": "три.wav",
  "хвала": "хвала.wav",
  "храна": "храна.wav",
  "један": "један.wav",
  "љубав": "љубав.wav"
 },
 "sv": {
  "ett": "ett.wav",
  "förlåt": "förlåt.wav",
  "hej": "hej.wav",
  "hej då": "hej_då.wav",
  "hur mycket": "hur_mycket.wav",
  "ja": "ja.wav",
  "kärlek": "kärlek.wav",
  "mat": "mat.wav",
  "nej": "nej.wav",
  "snälla": "snälla.wav",
  "tack": "tack.wav",
  "toalett": "toalett.wav",
  "tre": "tre.wav",
  "två": "två.wav",
  "vatten": "vatten.wav",
  "vän": "vän.wav"
 },
 "sw": {
  "asante": "asante.flac",
  "bei gani": "bei_gani.wav",
  "chakula": "chakula.flac",
  "choo": "choo.wav",
  "hapana": "hapana.wav",
  "jambo": "jambo.wav",
  "kwaheri": "kwaheri.wav",
  "maji": "maji.wav",
  "mbili": "mbili.wav",
  "moja": "moja.wav",
  "ndiyo": "ndiyo.wav",
  "rafiki": "rafiki.wav",
  "samahani": "samahani.wav",
  "tafadhali": "tafadhali.wav",
  "tatu": "tatu.wav",
  "upendo": "upendo.wav"
 },
 "ta": {
  "அன்பு": "அன_ப.wav",
  "ஆம்": "ஆம.wav",
  "இரண்டு": "இரண_ட.wav",
  "இல்லை": "இல_ல.wav",
  "உணவு": "உணவ.wav",
  "எவ்வளவு": "எவ_வளவ.wav",
  "ஒன்று": "ஒன_ற.wav",
  "தண்ணீர்": "தண_ண_ர.wav",
  "தயவுசெய்து": "தயவ_ச_ய_த.wav",
  "நண்பன்": "நண_பன.wav",
  "நன்றி": "நன_ற.wav",
  "மன்னிக்கவும்": "மன_ன_க_கவ_ம.wav",
  "மூன்று": "ம_ன_ற.wav",
  "வணக்கம்": "வணக_கம.wav"
 },
 "th": {
  "กรุณา": "กร_ณา.wav",
  "ขอบคุณ": "ขอบค_ณ.wav",
  "ขอโทษ": "ขอโทษ.wav",
  "ความรัก": "ความร_ก.wav",
  "น้ำ": "น_ำ.wav",
  "ลาก่อน": "ลาก_อน.wav",
  "สวัสดี": "สว_สด.wav",
  "สอง": "สอง.wav",
  "สาม": "สาม.wav",
  "หนึ่ง": "หน_ง.wav",
  "ห้องน้ำ": "ห_องน_ำ.wav",
  "อาหาร": "อาหาร.wav",
  "เท่าไร": "เท_าไร.wav",
  "เพื่อน": "เพ_อน.wav",
  "ใช่": "ใช.wav",
  "ไม่": "ไม.wav"
 },
 "tr": {
  "affedersiniz": "affedersiniz.wav",
  "arkadaş": "arkadaş.wav",
  "aşk": "aşk.wav",
  "bir": "bir.wav",
  "evet": "evet.wav",
  "hayır": "hayır.wav",
  "hoşça kal": "hoşça_kal.wav",
  "iki": "iki.wav",
  "lütfen": "lütfen.wav",
  "merhaba": "merhaba.wav",
  "ne kadar": "ne_kadar.wav",
  "su": "su.wav",
  "teşekkürler": "teşekkürler.wav",
  "tuvalet": "tuvalet.wav",
  "yemek": "yemek.wav",
  "üç": "üç.wav"
 },
 "uk": {
  "будь ласка": "будь_ласка.wav",
  "вибачте": "вибачте.wav",
  "вода": "вода.wav",
  "два": "два.wav",
  "до побачення": "до_побачення.wav",
  "друг": "друг.wav",
  "дякую": "дякую.wav",
  "любов": "любов.wav",
  "ні": "ні.wav",
  "один": "один.wav",
  "привіт": "привіт.wav",
  "скільки": "скільки.wav",
  "так": "так.wav",
  "три": "три.wav",
  "туалет": "туалет.wav",
  "їжа": "їжа.wav"
 },
 "ur": {
  "السلام علیکم": "السلام_علیکم.wav",
  "ایک": "ایک.wav",
  "باتھ روم": "باتھ_روم.wav",
  "تین": "تین.wav",
  "خدا حافظ": "خدا_حافظ.wav",
  "دو": "دو.wav",
  "دوست": "دوست.wav",
  "شکریہ": "شکریہ.wav",
  "محبت": "محبت.wav",
  "معاف کیجیے": "معاف_کیجیے.wav",
  "مہربانی": "مہربانی.wav",
  "نہیں": "نہیں.wav",
  "پانی": "پانی.wav",
  "کتنا": "کتنا.wav",
  "کھانا": "کھانا.wav",
  "ہاں": "ہاں.wav"
 },
 "vi": {
  "ba": "ba.wav",
  "bao nhiêu": "bao_nhiêu.wav",
  "bạn": "bạn.wav",
  "cảm ơn": "cảm_ơn.wav",
  "hai": "hai.wav",
  "không": "không.wav",
  "làm ơn": "làm_ơn.wav",
  "một": "một.wav",
  "nhà vệ sinh": "nhà_vệ_sinh.wav",
  "nước": "nước.wav",
  "thức ăn": "thức_ăn.wav",
  "tình yêu": "tình_yêu.wav",
  "tạm biệt": "tạm_biệt.wav",
  "vâng": "vâng.wav",
  "xin chào": "xin_chào.wav",
  "xin lỗi": "xin_lỗi.wav"
 },
 "zh": {
  "一": "一.wav",
  "三": "三.wav",
  "不客气": "不客气.wav",
  "不是": "不是.wav",
  "中国": "中国.wav",
  "二": "二.wav",
  "五": "五.wav",
  "你好": "你好.wav",
  "再见": "再见.wav",
  "名字": "名字.wav",
  "四": "四.wav",
  "多少钱": "多少钱.wav",
  "好吃": "好吃.wav",
  "学校": "学校.wav",
  "对不起": "对不起.wav",
  "很高兴": "很高兴.wav",
  "我不懂": "我不懂.wav",
  "我爱你": "我爱你.wav",
  "早上好": "早上好.wav",
  "是": "是.wav",
  "朋友": "朋友.wav",
  "水": "水.wav",
  "洗手间": "洗手间.wav",
  "火车站": "火车站.wav",
  "狗": "狗.wav",
  "猫": "猫.wav",
  "米饭": "米饭.wav",
  "老师": "老师.wav",
  "茶": "茶.wav",
  "谢谢": "谢谢.wav"
 }
};
window.RECORDINGS_SOURCE = {
 "af": {
  "asseblief": "made",
  "dankie": "made",
  "drie": "made",
  "een": "made",
  "hallo": "made",
  "hoeveel": "made",
  "ja": "made",
  "jammer": "made",
  "kos": "made",
  "liefde": "made",
  "nee": "made",
  "toilet": "made",
  "totsiens": "made",
  "twee": "made",
  "vriend": "made",
  "water": "made"
 },
 "am": {
  "ሁለት": "made",
  "ምግብ": "made",
  "ሰላም": "made",
  "ስንት": "made",
  "ሶስት": "made",
  "አመሰግናለሁ": "made",
  "አንድ": "made",
  "አዎ": "made",
  "አይደለም": "made",
  "እባክህ": "made",
  "ውሃ": "made",
  "ይቅርታ": "made",
  "ደህና ሁን": "made",
  "ጓደኛ": "made",
  "ፍቅር": "made"
 },
 "ar": {
  "آسف": "made",
  "أحبك": "made",
  "أربعة": "made",
  "اثنان": "made",
  "اسم": "made",
  "السلام عليكم": "made",
  "بيت": "made",
  "ثلاثة": "made",
  "جميل": "made",
  "حمام": "made",
  "خبز": "made",
  "خمسة": "made",
  "شاي": "made",
  "شكرا": "made",
  "صباح الخير": "made",
  "صديق": "made",
  "قطة": "made",
  "كم الثمن": "made",
  "لا": "made",
  "لا أفهم": "made",
  "لذيذ": "made",
  "مدرسة": "made",
  "مرحبا": "made",
  "مصر": "made",
  "مع السلامة": "made",
  "معلم": "made",
  "من فضلك": "made",
  "نعم": "made",
  "واحد": "made"
 },
 "bg": {
  "благодаря": "made",
  "вода": "made",
  "да": "made",
  "две": "made",
  "довиждане": "made",
  "едно": "made",
  "здравей": "made",
  "извинете": "made",
  "колко": "made",
  "любов": "made",
  "моля": "made",
  "не": "made",
  "приятел": "made",
  "тоалетна": "made",
  "три": "made",
  "храна": "made"
 },
 "bn": {
  "এক": "made",
  "কত": "made",
  "খাবার": "made",
  "জল": "made",
  "তিন": "made",
  "দয়া করে": "made",
  "দুঃখিত": "made",
  "দুই": "made",
  "ধন্যবাদ": "made",
  "নমস্কার": "made",
  "না": "made",
  "বন্ধু": "made",
  "বাথরুম": "made",
  "বিদায়": "made",
  "ভালোবাসা": "made",
  "হ্যাঁ": "made"
 },
 "ca": {
  "adéu": "made",
  "aigua": "made",
  "amic": "made",
  "amor": "made",
  "dos": "made",
  "gràcies": "made",
  "hola": "made",
  "lavabo": "made",
  "menjar": "made",
  "no": "made",
  "perdó": "made",
  "quant": "made",
  "si us plau": "made",
  "sí": "made",
  "tres": "made",
  "un": "made"
 },
 "cs": {
  "ahoj": "made",
  "ano": "made",
  "dva": "made",
  "děkuji": "made",
  "jeden": "made",
  "jídlo": "made",
  "kolik": "made",
  "láska": "made",
  "na shledanou": "made",
  "ne": "made",
  "promiňte": "made",
  "prosím": "made",
  "přítel": "made",
  "tři": "made",
  "voda": "made",
  "záchod": "made"
 },
 "da": {
  "en": "made",
  "farvel": "made",
  "hej": "made",
  "hvor meget": "made",
  "ja": "made",
  "kærlighed": "made",
  "mad": "made",
  "nej": "made",
  "tak": "made",
  "to": "made",
  "toilet": "made",
  "tre": "made",
  "undskyld": "made",
  "vand": "made",
  "ven": "made",
  "vær så god": "made"
 },
 "de": {
  "Essen": "human",
  "Freund": "human",
  "Liebe": "human",
  "Toilette": "human",
  "Wasser": "human",
  "bitte": "human",
  "danke": "human",
  "drei": "made",
  "eins": "human",
  "entschuldigung": "made",
  "hallo": "human",
  "ja": "human",
  "nein": "made",
  "tschüss": "human",
  "wie viel": "human",
  "zwei": "human"
 },
 "el": {
  "Ελλάδα": "made",
  "ένα": "made",
  "αντίο": "made",
  "γάτα": "made",
  "γεια σου": "made",
  "δάσκαλος": "made",
  "δεν καταλαβαίνω": "made",
  "δύο": "made",
  "ευχαριστώ": "made",
  "καλημέρα": "made",
  "καλησπέρα": "made",
  "καφές": "made",
  "ναι": "made",
  "νερό": "made",
  "νόστιμο": "made",
  "πέντε": "made",
  "παρακαλώ": "made",
  "πόσο κάνει": "made",
  "σκύλος": "made",
  "σπίτι": "made",
  "συγγνώμη": "made",
  "σχολείο": "made",
  "τέσσερα": "made",
  "τουαλέτα": "made",
  "τρία": "made",
  "φίλος": "made",
  "ψωμί": "made",
  "ωραία": "made",
  "όνομα": "made",
  "όχι": "made"
 },
 "en": {
  "food": "made",
  "friend": "made",
  "goodbye": "made",
  "hello": "made",
  "how much": "made",
  "love": "made",
  "no": "made",
  "one": "made",
  "please": "made",
  "sorry": "made",
  "thank you": "made",
  "three": "made",
  "toilet": "made",
  "two": "made",
  "water": "made",
  "yes": "made"
 },
 "eo": {
  "akvo": "made",
  "amiko": "made",
  "amo": "made",
  "bonvolu": "made",
  "dankon": "made",
  "du": "made",
  "jes": "made",
  "kiom": "made",
  "manĝaĵo": "made",
  "ne": "made",
  "necesejo": "made",
  "pardonu": "made",
  "saluton": "made",
  "tri": "made",
  "unu": "made",
  "ĝis revido": "made"
 },
 "es": {
  "España": "made",
  "adiós": "made",
  "agua": "made",
  "amigo": "made",
  "baño": "made",
  "buenos días": "made",
  "café": "made",
  "casa": "made",
  "cinco": "made",
  "cuatro": "made",
  "cuánto cuesta": "made",
  "delicioso": "made",
  "dos": "made",
  "escuela": "made",
  "feliz": "made",
  "gracias": "made",
  "hola": "made",
  "lo siento": "made",
  "maestro": "made",
  "no": "made",
  "no entiendo": "made",
  "nombre": "made",
  "pan": "made",
  "perro": "made",
  "por favor": "made",
  "sí": "made",
  "te quiero": "made",
  "tres": "made",
  "uno": "made"
 },
 "fa": {
  "آب": "made",
  "ببخشید": "made",
  "بله": "made",
  "خداحافظ": "made",
  "دستشویی": "made",
  "دو": "made",
  "دوست": "made",
  "سلام": "made",
  "سه": "made",
  "عشق": "made",
  "غذا": "made",
  "لطفا": "made",
  "ممنون": "made",
  "نه": "made",
  "چند": "made",
  "یک": "made"
 },
 "fi": {
  "anteeksi": "made",
  "ei": "made",
  "hei": "made",
  "kaksi": "made",
  "kiitos": "made",
  "kolme": "made",
  "kyllä": "made",
  "näkemiin": "made",
  "ole hyvä": "made",
  "paljonko": "made",
  "rakkaus": "made",
  "ruoka": "made",
  "vesi": "made",
  "vessa": "made",
  "yksi": "made",
  "ystävä": "made"
 },
 "fr": {
  "France": "made",
  "ami": "made",
  "au revoir": "made",
  "bonjour": "made",
  "bonsoir": "made",
  "café": "made",
  "chat": "made",
  "chien": "made",
  "cinq": "made",
  "combien": "made",
  "deux": "made",
  "délicieux": "made",
  "eau": "made",
  "heureux": "made",
  "ja": "made",
  "je ne comprends pas": "made",
  "maison": "made",
  "merci": "made",
  "nom": "made",
  "non": "made",
  "oui": "made",
  "pain": "made",
  "pardon": "made",
  "professeur": "made",
  "quatre": "made",
  "toilettes": "made",
  "trois": "made",
  "un": "made",
  "école": "made"
 },
 "he": {
  "אהבה": "made",
  "אוכל": "made",
  "אחד": "made",
  "בבקשה": "made",
  "חבר": "made",
  "כמה": "made",
  "כן": "made",
  "לא": "made",
  "להתראות": "made",
  "מים": "made",
  "סליחה": "made",
  "שירותים": "made",
  "שלום": "made",
  "שלוש": "made",
  "שתיים": "made",
  "תודה": "made"
 },
 "hi": {
  "अच्छा": "made",
  "एक": "made",
  "कितने का है": "made",
  "कुत्ता": "made",
  "कृपया": "made",
  "घर": "made",
  "चाय": "made",
  "चार": "made",
  "चावल": "made",
  "तीन": "made",
  "दो": "made",
  "दोस्त": "made",
  "धन्यवाद": "made",
  "नमस्ते": "made",
  "नहीं": "made",
  "नाम": "made",
  "पाँच": "made",
  "पानी": "made",
  "प्यार": "made",
  "फिर मिलेंगे": "made",
  "बिल्ली": "made",
  "भारत": "made",
  "माफ़ कीजिए": "made",
  "शिक्षक": "made",
  "शौचालय": "made",
  "समझ नहीं आया": "made",
  "सुप्रभात": "made",
  "स्कूल": "made",
  "स्वादिष्ट": "made",
  "हाँ": "made"
 },
 "hr": {
  "bok": "made",
  "da": "made",
  "doviđenja": "made",
  "dva": "made",
  "hrana": "made",
  "hvala": "made",
  "jedan": "made",
  "koliko": "made",
  "ljubav": "made",
  "molim": "made",
  "ne": "made",
  "oprostite": "made",
  "prijatelj": "made",
  "tri": "made",
  "voda": "made",
  "zahod": "made"
 },
 "ht": {
  "bonjou": "made",
  "de": "made",
  "dlo": "made",
  "eskize m": "made",
  "konbyen": "made",
  "lanmou": "made",
  "manje": "made",
  "mèsi": "made",
  "non": "made",
  "orevwa": "made",
  "souple": "made",
  "twa": "made",
  "twalèt": "made",
  "wi": "made",
  "youn": "made",
  "zanmi": "made"
 },
 "hu": {
  "barát": "made",
  "bocsánat": "made",
  "egy": "made",
  "három": "made",
  "igen": "made",
  "kettő": "made",
  "kérem": "made",
  "köszönöm": "made",
  "mennyibe": "made",
  "mosdó": "made",
  "nem": "made",
  "szerelem": "made",
  "szia": "made",
  "viszlát": "made",
  "víz": "made",
  "étel": "made"
 },
 "hy": {
  "այո": "made",
  "բարև": "made",
  "երեք": "made",
  "երկու": "made",
  "զուգարան": "made",
  "ընկեր": "made",
  "ինչքան": "made",
  "խնդրեմ": "made",
  "մեկ": "made",
  "ներողություն": "made",
  "շնորհակալություն": "made",
  "ոչ": "made",
  "ուտելիք": "made",
  "ջուր": "made",
  "սեր": "made",
  "ցտեսություն": "made"
 },
 "id": {
  "air": "made",
  "berapa": "made",
  "cinta": "made",
  "dua": "made",
  "halo": "made",
  "maaf": "made",
  "makanan": "made",
  "satu": "made",
  "selamat tinggal": "made",
  "teman": "made",
  "terima kasih": "made",
  "tidak": "made",
  "tiga": "made",
  "toilet": "made",
  "tolong": "made",
  "ya": "made"
 },
 "it": {
  "acqua": "made",
  "amico": "made",
  "amore": "made",
  "arrivederci": "made",
  "bagno": "made",
  "ciao": "made",
  "cibo": "made",
  "due": "made",
  "grazie": "made",
  "no": "made",
  "per favore": "made",
  "quanto": "made",
  "scusa": "made",
  "sì": "made",
  "tre": "made",
  "uno": "made"
 },
 "ja": {
  "ありがとう": "made",
  "いいえ": "made",
  "いくらですか": "made",
  "いただきます": "made",
  "おはようございます": "made",
  "お茶": "made",
  "お願いします": "made",
  "こんにちは": "made",
  "こんばんは": "made",
  "ご飯": "made",
  "さようなら": "made",
  "すみません": "made",
  "はい": "made",
  "またね": "made",
  "トイレはどこですか": "made",
  "一": "made",
  "三": "made",
  "二": "made",
  "五": "made",
  "元気ですか": "made",
  "先生": "made",
  "分かりません": "made",
  "友達": "made",
  "名前": "made",
  "四": "made",
  "大丈夫": "made",
  "学校": "made",
  "愛": "made",
  "日本": "made",
  "楽しい": "made",
  "水": "made",
  "犬": "made",
  "猫": "made",
  "美味しい": "made",
  "駅": "made"
 },
 "ka": {
  "არა": "made",
  "ბოდიши": "made",
  "გამარჯობა": "made",
  "გთხოვთ": "made",
  "ერთი": "made",
  "კი": "made",
  "მადლობა": "made",
  "მეგობარი": "made",
  "ნახვამდის": "made",
  "ორი": "made",
  "რამდენი": "made",
  "სამი": "made",
  "საჭმელი": "made",
  "სიყვარული": "made",
  "ტუალეტი": "made",
  "წყალი": "made"
 },
 "ko": {
  "감사합니다": "made",
  "고양이": "made",
  "괜찮아요": "made",
  "김치": "made",
  "네": "made",
  "넷": "made",
  "다섯": "made",
  "둘": "made",
  "맛있어요": "made",
  "몰라요": "made",
  "물": "made",
  "밥": "made",
  "사랑해요": "made",
  "선생님": "made",
  "셋": "made",
  "아니요": "made",
  "안녕하세요": "made",
  "안녕히 가세요": "made",
  "얼마예요": "made",
  "여기": "made",
  "이름": "made",
  "잘 자요": "made",
  "죄송합니다": "made",
  "집": "made",
  "친구": "made",
  "하나": "made",
  "학교": "made",
  "한국": "made",
  "행복해요": "made",
  "화장실": "made"
 },
 "mn": {
  "баярлалаа": "made",
  "баяртай": "made",
  "гуйя": "made",
  "гурав": "made",
  "найз": "made",
  "нэг": "made",
  "сайн байна уу": "made",
  "тийм": "made",
  "ус": "made",
  "уучлаарай": "made",
  "хайр": "made",
  "хоол": "made",
  "хоёр": "made",
  "хэд": "made",
  "үгүй": "made"
 },
 "mr": {
  "एक": "made",
  "किती": "made",
  "कृपया": "made",
  "जेवण": "made",
  "तीन": "made",
  "दोन": "made",
  "धन्यवाद": "made",
  "नमस्कार": "made",
  "नाही": "made",
  "पाणी": "made",
  "प्रेम": "made",
  "माफ करा": "made",
  "मित्र": "made",
  "येतो": "made",
  "होय": "made"
 },
 "ne": {
  "एक": "made",
  "कति": "made",
  "कृपया": "made",
  "खाना": "made",
  "तीन": "made",
  "दुई": "made",
  "धन्यवाद": "made",
  "नमस्ते": "made",
  "पानी": "made",
  "माफ गर्नुहोस्": "made",
  "माया": "made",
  "शौचालय": "made",
  "साथी": "made",
  "हो": "made",
  "होइन": "made"
 },
 "nl": {
  "alsjeblieft": "made",
  "dank je": "made",
  "doei": "made",
  "drie": "made",
  "een": "made",
  "eten": "made",
  "hallo": "made",
  "hoeveel": "made",
  "ja": "made",
  "liefde": "made",
  "nee": "made",
  "sorry": "made",
  "toilet": "made",
  "twee": "made",
  "vriend": "made",
  "water": "made"
 },
 "no": {
  "en": "made",
  "ha det": "made",
  "hei": "made",
  "hvor mye": "made",
  "ja": "made",
  "kjærlighet": "made",
  "mat": "made",
  "nei": "made",
  "takk": "made",
  "to": "made",
  "toalett": "made",
  "tre": "made",
  "unnskyld": "made",
  "vann": "made",
  "venn": "made",
  "vær så snill": "made"
 },
 "pl": {
  "cześć": "made",
  "do widzenia": "made",
  "dwa": "made",
  "dziękuję": "made",
  "ile": "made",
  "jeden": "made",
  "jedzenie": "made",
  "miłość": "made",
  "nie": "made",
  "proszę": "made",
  "przepraszam": "made",
  "przyjaciel": "made",
  "tak": "made",
  "toaleta": "made",
  "trzy": "made",
  "woda": "made"
 },
 "pt": {
  "amigo": "made",
  "amor": "made",
  "banheiro": "made",
  "comida": "made",
  "desculpe": "made",
  "dois": "made",
  "não": "made",
  "obrigado": "made",
  "olá": "made",
  "por favor": "made",
  "quanto": "made",
  "sim": "made",
  "tchau": "made",
  "três": "made",
  "um": "made",
  "água": "made"
 },
 "ro": {
  "apă": "made",
  "cât": "made",
  "da": "made",
  "doi": "made",
  "dragoste": "made",
  "la revedere": "made",
  "mulțumesc": "made",
  "mâncare": "made",
  "nu": "made",
  "prieten": "made",
  "salut": "made",
  "scuze": "made",
  "toaletă": "made",
  "trei": "made",
  "unu": "made",
  "vă rog": "made"
 },
 "ru": {
  "Россия": "human",
  "вкусно": "made",
  "вода": "human",
  "вокзал": "made",
  "да": "human",
  "два": "human",
  "до свидания": "made",
  "доброе утро": "human",
  "дом": "made",
  "друг": "made",
  "здравствуйте": "human",
  "извините": "made",
  "имя": "made",
  "нет": "made",
  "один": "made",
  "пожалуйста": "made",
  "привет": "human",
  "пять": "made",
  "сколько стоит": "made",
  "собака": "made",
  "спасибо": "made",
  "три": "made",
  "туалет": "made",
  "учитель": "made",
  "хлеб": "made",
  "хорошо": "made",
  "чай": "made",
  "четыре": "made",
  "школа": "made",
  "я не понимаю": "made",
  "я тебя люблю": "made"
 },
 "sk": {
  "ahoj": "made",
  "dovidenia": "made",
  "dva": "made",
  "jeden": "made",
  "jedlo": "made",
  "koľko": "made",
  "láska": "made",
  "nie": "made",
  "prepáčte": "made",
  "priateľ": "made",
  "prosím": "made",
  "tri": "made",
  "voda": "made",
  "záchod": "made",
  "áno": "made",
  "ďakujem": "made"
 },
 "so": {
  "biyo": "made",
  "cunto": "made",
  "fadlan": "made",
  "haa": "made",
  "immisa": "made",
  "jacayl": "made",
  "kow": "made",
  "laba": "made",
  "mahadsanid": "made",
  "maya": "made",
  "musqul": "made",
  "nabadgelyo": "made",
  "raali ahow": "made",
  "saaxiib": "made",
  "saddex": "made",
  "salaan": "made"
 },
 "sq": {
  "banjo": "made",
  "dashuri": "made",
  "dy": "made",
  "faleminderit": "made",
  "jo": "made",
  "ju lutem": "made",
  "mik": "made",
  "mirupafshim": "made",
  "më fal": "made",
  "një": "made",
  "po": "made",
  "përshëndetje": "made",
  "sa": "made",
  "tre": "made",
  "ujë": "made",
  "ushqim": "made"
 },
 "sr": {
  "вода": "made",
  "да": "made",
  "два": "made",
  "довиђења": "made",
  "здраво": "made",
  "извините": "made",
  "колико": "made",
  "молим": "made",
  "не": "made",
  "пријатељ": "made",
  "тоалет": "made",
  "три": "made",
  "хвала": "made",
  "храна": "made",
  "један": "made",
  "љубав": "made"
 },
 "sv": {
  "ett": "made",
  "förlåt": "made",
  "hej": "made",
  "hej då": "made",
  "hur mycket": "made",
  "ja": "made",
  "kärlek": "made",
  "mat": "made",
  "nej": "made",
  "snälla": "made",
  "tack": "made",
  "toalett": "made",
  "tre": "made",
  "två": "made",
  "vatten": "made",
  "vän": "made"
 },
 "sw": {
  "asante": "human",
  "bei gani": "made",
  "chakula": "human",
  "choo": "made",
  "hapana": "made",
  "jambo": "made",
  "kwaheri": "made",
  "maji": "made",
  "mbili": "made",
  "moja": "made",
  "ndiyo": "made",
  "rafiki": "made",
  "samahani": "made",
  "tafadhali": "made",
  "tatu": "made",
  "upendo": "made"
 },
 "ta": {
  "அன்பு": "made",
  "ஆம்": "made",
  "இரண்டு": "made",
  "இல்லை": "made",
  "உணவு": "made",
  "எவ்வளவு": "made",
  "ஒன்று": "made",
  "தண்ணீர்": "made",
  "தயவுசெய்து": "made",
  "நண்பன்": "made",
  "நன்றி": "made",
  "மன்னிக்கவும்": "made",
  "மூன்று": "made",
  "வணக்கம்": "made"
 },
 "th": {
  "กรุณา": "made",
  "ขอบคุณ": "made",
  "ขอโทษ": "made",
  "ความรัก": "made",
  "น้ำ": "made",
  "ลาก่อน": "made",
  "สวัสดี": "made",
  "สอง": "made",
  "สาม": "made",
  "หนึ่ง": "made",
  "ห้องน้ำ": "made",
  "อาหาร": "made",
  "เท่าไร": "made",
  "เพื่อน": "made",
  "ใช่": "made",
  "ไม่": "made"
 },
 "tr": {
  "affedersiniz": "made",
  "arkadaş": "made",
  "aşk": "made",
  "bir": "made",
  "evet": "made",
  "hayır": "made",
  "hoşça kal": "made",
  "iki": "made",
  "lütfen": "made",
  "merhaba": "made",
  "ne kadar": "made",
  "su": "made",
  "teşekkürler": "made",
  "tuvalet": "made",
  "yemek": "made",
  "üç": "made"
 },
 "uk": {
  "будь ласка": "made",
  "вибачте": "made",
  "вода": "made",
  "два": "made",
  "до побачення": "made",
  "друг": "made",
  "дякую": "made",
  "любов": "made",
  "ні": "made",
  "один": "made",
  "привіт": "made",
  "скільки": "made",
  "так": "made",
  "три": "made",
  "туалет": "made",
  "їжа": "made"
 },
 "ur": {
  "السلام علیکم": "made",
  "ایک": "made",
  "باتھ روم": "made",
  "تین": "made",
  "خدا حافظ": "made",
  "دو": "made",
  "دوست": "made",
  "شکریہ": "made",
  "محبت": "made",
  "معاف کیجیے": "made",
  "مہربانی": "made",
  "نہیں": "made",
  "پانی": "made",
  "کتنا": "made",
  "کھانا": "made",
  "ہاں": "made"
 },
 "vi": {
  "ba": "made",
  "bao nhiêu": "made",
  "bạn": "made",
  "cảm ơn": "made",
  "hai": "made",
  "không": "made",
  "làm ơn": "made",
  "một": "made",
  "nhà vệ sinh": "made",
  "nước": "made",
  "thức ăn": "made",
  "tình yêu": "made",
  "tạm biệt": "made",
  "vâng": "made",
  "xin chào": "made",
  "xin lỗi": "made"
 },
 "zh": {
  "一": "made",
  "三": "made",
  "不客气": "made",
  "不是": "made",
  "中国": "made",
  "二": "made",
  "五": "made",
  "你好": "made",
  "再见": "made",
  "名字": "made",
  "四": "made",
  "多少钱": "made",
  "好吃": "made",
  "学校": "made",
  "对不起": "made",
  "很高兴": "made",
  "我不懂": "made",
  "我爱你": "made",
  "早上好": "made",
  "是": "made",
  "朋友": "made",
  "水": "made",
  "洗手间": "made",
  "火车站": "made",
  "狗": "made",
  "猫": "made",
  "米饭": "made",
  "老师": "made",
  "茶": "made",
  "谢谢": "made"
 }
};
